### PR TITLE
support ng-required validator - fixes #258

### LINKED ISSUE #258: ng-required not validating form on submit
when using ui-select with ng-required or required attribute, form is not validating on submit action.

### PR DESCRIPTION
**Pull request by ohjames**
fixes #258, at least for single-entry ui-selects.

I took the work from @zgbjgg but applied to the correct files in src and fixed the whitespace/grammar.

I've verified the tests still pass with `gulp` but didn't include the changed files in `dist` in that commit. Would be very grateful if you could release 0.19.2 with this fix.

### CODE REVIEW

**Comment by ohjames** [comment]
Let me know if you want me to commit the files in `dist` and if so, whether I should merge the commits together or apply the updated `dist` files in a second commit.

**Comment by ohjames** [comment]
Sorry ignore this PR for now, after testing the changes they don't seem to work for me.

**Comment by ohjames** [comment]
I'll try again with a new PR based on my own work... I'm not seeing any of the `form[fieldName]` fields.

**Comment by user378230** [comment]
You may want to review angular documentation for ngRequired:  https://docs.angularjs.org/api/ng/directive/ngRequired

Note all PRs need tests as well.

**Pull request closed without merging**
