### PR TITLE
Stop propagation when pressing ENTER key from dropdown

### PR DESCRIPTION
**Pull request by loverajoel**
## What does this Pull Request Do?

Fix the event propagation when pressing enter key from dropdown

## How should this be manually tested?

Run the tests and try the demos

## What are the relevant issues?

https://github.com/angular-ui/ui-select/issues/862

### CODE REVIEW

**Comment by loverajoel** [comment]
I found this related pr https://github.com/angular-ui/ui-select/pull/866 and this issue https://github.com/angular-ui/ui-select/issues/862

**Comment by aschelstraete** [comment]
This works awesome!

**Comment by wzomer** [comment]
Perfect, thanks!

**Comment by brianfeister** [comment]
See my comment from #862/issuecomment-98151471

**Comment by loverajoel** [comment]
@brianfeister I made another pr with the proposal for esc + enter keys https://github.com/angular-ui/ui-select/pull/901

**Comment by brianfeister** [comment]
Hmm... why a new PR?  You can just push to this branch right?

**Comment by brianfeister** [comment]
Ok, that one's new, fine then.  Closing in favor of #901.

**Pull request closed without merging**
