### PR TITLE
fix #1128 (AngularJS 1.4.3 TypeError: Cannot read property 'style' of undefined)

### LINKED ISSUE #1128: AngularJS 1.4.3 TypeError: Cannot read property 'style' of undefined
Hi, 

When selecting in single or multiselect i get TypeError: Cannot read property 'style' of undefined at Object.fn (select.js:1024).

I am running AngularJS 1.4.3, im guessing dropdown = angular.element(element).querySelectorAll('.ui-select-dropdown'); cant find correct element. Any ideas?

 <ui-select multiple ng-model="connectingDimensionValue.Value" theme="select2" name="connectingDimensionValue">
                <ui-select-match placeholder="Choose X">{{$item.Name}}</ui-select-match>
                <ui-select-choices repeat="connectingDimensionValue.Value as connectingDimensionValue in connectingDimensionValues | filter: $select.search">
                  <div ng-bind-html="connectingDimensionValue.Name"></div>
                </ui-select-choices>
              </ui-select>

### PR DESCRIPTION
**Pull request by cjroth**

### CODE REVIEW

**Comment by carlos-** [comment]
+1

**Comment by Luxor** [comment]
+1

**Comment by SajjadGit** [comment]
+1

**Comment by wesleycho** [comment]
Closing as this looks fixed in `master`: https://github.com/angular-ui/ui-select/blob/d5e30fb1227678348f7435d9864356ed0f75f690/src/uiSelectDirective.js#L323-L325

**Pull request closed without merging**
