### PR TITLE
allow cancellation of selection

### LINKED ISSUE #760: cancel selection
How can I cancel item selection?

I have some items in my dropdown that I need to respond to, however I don't want them to change the currently selected value. 

Probably the best way would be to cancel selection when on-select callback returns false, would this be easy to add?

### PR DESCRIPTION
**Pull request by parliament718**
allow cancel selection by returning false from on-select callback closes #760

### CODE REVIEW

**Comment by dimirc** [comment]
Pls dont change /dist files but only /src

**Comment by parliament718** [comment]
sorry don't really know what I'm doing yet here. When I looked at src the code didn't even look the same?
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L272

Can this fix be incorporated somehow?

**Comment by dimirc** [comment]
Maybe we could move the [broadcast](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L267) after the onSelectCallback but inside the $timeout

**Comment by parliament718** [comment]
Should I do that?

**Comment by allenm** [comment]
I also need this , expect this PR to be merged .

**Comment by qcmatsuoka** [comment]
+1

**Comment by martinoss** [comment]
+1, need this too for tagging. I need to be able to cancel an insertion of an invalid value, either by the tagging function or on-selection.

**Comment by wesleycho** [comment]
Remove the changes to `dist`, and make the changes to the appropriate files in `src`.

**Comment by Jefiozie** [comment]
If i'm correct this PR can be closed as the original issue has been closed. If not please verify with latest version and make a new issue/PR.

Thanks

**Comment by cyrilchapon** [comment]
This is not ok.
Issue has been closed without been resolved.

**Pull request closed without merging**
