### PR TITLE
Add acessibility

### PR DESCRIPTION
**Pull request by aeisenberg**
Pull request for Issue #527.

### CODE REVIEW

**Comment by brianfeister** [comment]
Thanks @aeisenberg. A cursory glance of this looks good.  I'd love a second set of eyes on it @amcdnl.  In the meantime can you rebase?

**Comment by aeisenberg** [comment]
Rebased.

**Comment by amcdnl** [comment]
Overall it looks good.  There is a ton of bindings introduced but I dont know what/if any impact that might have on perf.  I like the generated ids concept too.

Have you checked out: https://docs.angularjs.org/api/ngAria ... was introduced recently, haven't used it myself yet.

**Comment by aeisenberg** [comment]
Thanks for the review.  I was not aware of ngAria. I'll have to take a
look. ui-select needs to work on 1.2.x, so I don't think it would be
appropriate in this project.

**Comment by amcdnl** [comment]
Merged

**Comment by 0xF013** [comment]
@aeisenberg  :+1:
@amcdnl ngAria does a lot of stuff but it doesn't cover sophisticated cases like marking the active descendant of the combobox (meaning that the screen reader won't tell the user there are autocompleted options or which of them is currently selected).

Another accessibility issue is the multiple selection. It allows arrow navigation and backspace to delete the selected item but the selected block is not focused, so the screenreader doesn't know that you actually selected something. That might be addressed in a separate PR

**Comment by amcdnl** [comment]
@0xF013 Ya, lets do that in a separate issue / pr

**Comment by lindenthal** [comment]
Hi guys,
what is the status here? We use UI select in openproject.org. And we need it to be fully accessible. Can we help out?
Regards
Niels

**Comment by amcdnl** [comment]
This was merged. ^^^

**Pull request merged**
