### PR TITLE
fixed declining tagging via returning null #755

### PR DESCRIPTION
**Pull request by shoaibmerchant**
Just a small fix to the tagging code. All tests are passing.

The ui-select module has been a lifesaver, thanks!

### CODE REVIEW

**Comment by shoaibmerchant** [comment]
Refer to https://github.com/angular-ui/ui-select/issues/755

**Comment by LeleDev** [comment]
+1

**Comment by icfantv** [comment]
@shoaibmerchant, are you able to rebase this?  thanks.

**Comment by Jefiozie** [comment]
@aaronroberson or @user378230  cannot reproduce this issue any more maybe close it down as #755 
is already closed?

**Pull request closed without merging**
