### PR TITLE
Added add-all and clear functionality

### PR DESCRIPTION
**Pull request by maikdiepenbroek**
As tried before, i implemented add all and clear functionality. These can be added by attribute: clear-all and select-all.

By adding them with : true or false value they contain default text. It's possible to enter custom label text.

### CODE REVIEW

**Comment by maikdiepenbroek** [comment]
Could this be merged please ?

**Comment by maikdiepenbroek** [comment]
Removed Dist changes

**Comment by maikdiepenbroek** [comment]
@brianfeister Could this one be merged soon please, or is there something blocking this ?

**Comment by cdjackson** [comment]
Just a note that you have removed the files in Dist - they should have instead been reset. This still couldn't be merged until this is resolved.

**Comment by wesleycho** [comment]
Undo all changes to `dist`, and rebase off of current `master`.

**Comment by user378230** [comment]
Closing, lack of tests and conflicts.

**Pull request closed without merging**
