### PR TITLE
Implemantation of Issue #267: Custom Template for Group Labels

### PR DESCRIPTION
**Pull request by swissmanu**
- new directive `uiSelectGroup` for customizing the item groups header template.
- if no custom group template is given, a default fallback to $group.name is used instead.
- see `examples/demo-groupby.html` for further explanations

### CODE REVIEW

**Comment by swissmanu** [comment]
any interest in this?

**Comment by Envek** [comment]
I have interest on this, thank you very much for your work — I currently pulled it on my fork and playing with it. IMO, this is must have feature.

I've found one issue: for some reason `ng-repeat` directive does not work inside of `ui-select-group` directive (yeah, I'm crazy and I need to have group labels to be huge). And I do not know why.

**Comment by Envek** [comment]
Here is an example that illustrates problem with ng-repeat: http://plnkr.co/3fGeRhzjXl1CYHZhcDcO

By the way it's a nice example of custom templates for group labels, I think.

**Comment by wesleycho** [comment]
This needs rebasing, as well as unit tests.

**Pull request closed without merging**
