### PR TITLE
feat(choices): add null option support

### LINKED ISSUE #302: Provide option to add no-value choice
Angular.js [select directive](https://docs.angularjs.org/api/ng/directive/select) have a convenient way to define null-value option. If you put `<option>` tag without value inside `<select>`, it will be treated as null-option which sets model value to `null`.
It is useful sometimes to provide user ability to reset selected value. Now I have to implicitly add that item to other choices in repeat.

```js
$scope.persons = [{"id": null, "name": "No person"}].concat(otherPersons)
```
```html
<ui-select ng-model="form.person">
    <ui-select-match placeholder="Select person...">{{$select.selected.name}}</ui-select-match>
    <ui-select-choices repeat="person.id as person in persons">{{person.title}}</ui-select-choices>
</ui-select>
```
I don't want to do it and it would be good if you will have an option for provide this option through html, for example
```html
<ui-select ng-model="form.person">
    <ui-select-match placeholder="Select person...">{{$select.selected.name}}</ui-select-match>
    <ui-select-null-choice>No person</ui-select-null-choice>
    <ui-select-choices repeat="person.id as person in persons">{{person.title}}</ui-select-choices>
</ui-select>
```
It is similar to select directive logic and looks good for me. What do you think?

### PR DESCRIPTION
**Pull request by dlukez**
Needed this feature so decided to implement it. I toyed with a few different solutions and boiled it down to this (doesn't look like much, but it took me quite a while to get to this).

This solution requires that the "null" option is a typical item present in the array so that we have flexibility in filtering and displaying it without having to write a bunch of conditional statements. We then use the "null-option" directive on the "ui-select-choices" element to mark our null option. When the option is selected, the model is set to null (and vice versa).

An additional helper option is included - "loose-null" - which tells ui-select to treat undefined and null as the same. In this case, if the model value is undefined, the null option will still be displayed. Just add
"loose-null" on the "ui-select-choices" element.

See http://plnkr.co/edit/7nmBRicsmH33E55sSomz?p=preview.

Happy to discuss implementation specifics, thought I'd open this PR to get the ball rolling. Yet to write unit tests... Could anyone help with this?

### CODE REVIEW

**Comment by dlukez** [comment]
Mm, may not have been as relevant to #302 as I thought after having another read. May take another look at this at some point. If we want to include the null-option in the filtering things might be tough since the filtering happens outside of ui-select itself.

**Comment by dimirc** [comment]
If `nullOption` is used, then placeholder won't work or when will it be shown?

**Comment by dlukez** [comment]
The placeholder would be shown if "loose-null" isn't used and the value is undefined. I agree that this relationship between placeholder/null-option should probably be thought about further.

**Comment by dlukez** [comment]
Gonna close this for now to make sure it's not accidentally merged before it's ready. A discussion is still on going in #302 on this

**Pull request closed without merging**
