### PR TITLE
Corrected window.onbeforeunload firing in IE9

### PR DESCRIPTION
**Pull request by bricox**
...) call.  In IE9 this causes the window.onbeforeunload to fire on every selection, which could cause some unintended consiquences.

### CODE REVIEW

**Comment by abobwhite** [comment]
+1 !!! This is a major issue in my app.

**Comment by abobwhite** [comment]
...After looking through the current version of ui-select on your changed files, it appears the only change that hasn't already made it into master is your removal of:

```href="javascript:void(0)"``` from the template. I removed this on my local copy and it has fixed the problem.  If you rebase this, that should be the only change and I would assume this could get merged quickly.

**Comment by dimirc** [comment]
@abobwhite maybe you could help doing a new PR with that change?

**Comment by abobwhite** [comment]
@dimirc I would love to. The instructions for contributing seem a bit thin. Just install gulp, fork the repo, npm install, bower install, change code, and run tests? (I am not sure what I need to do to run tests).

**Comment by abobwhite** [comment]
@dimirc I am trying to do `bower install` and it's failing to get bower-angular....this should have been pretty simple. Do you know anything about why this isn't working? Obviously I can't build/test without angular.

**Comment by bricox** [comment]
Hey.  Sorry, I didn't mean to ignore this...

Did you get what you needed and get the change merged?  If not I can submit another pull request.

**Comment by abobwhite** [comment]
I think this issue is still out there. For some reason I couldn't get my bower install to work correctly to make the pull request. If you could update your pull request to just remove ```href="javascript:void(0)"``` that is all that is needed. It appears other merges have already been applied to fix your other changes.

**Comment by abobwhite** [comment]
@bricox Did you create a new pull request for that small change?

**Comment by macem** [comment]
The same problem i have on IE10. I removed javascript:void and it working https://github.com/macem/ui-select/commit/a3e4fb2502610c0c9bb48026250e7507139b4b80

**Comment by wesleycho** [comment]
Closing, as this looks fixed in `master`: https://github.com/angular-ui/ui-select/blob/e65995f1eb2e190e71c9226a2f754671a7277c86/src/bootstrap/choices.tpl.html#L9

**Pull request closed without merging**
