### PR TITLE
fixed pasting issue with generic ClipboardEvent in tagging mode

### PR DESCRIPTION
**Pull request by pyu10055**
fixed pasting issue with generic ClipboardEvent in tagging mode, and allow pasting when the tagging function is not defined.

### CODE REVIEW

**Comment by pyu10055** [comment]
fixing bugs #704, #789, #848

**Comment by faisalferoz** [comment]
+1 any chance of this getting merged?

**Comment by pyu10055** [comment]
bump, can someone take look at this fix?

**Comment by dmitry-dedukhin** [comment]
Actually, https://github.com/angular-ui/ui-select/issues/704 is not fixed by this change.
Paste handler immediately calls ctrl.select in loop and in case tagging-label="false" ctrl.select tries to parse text from ctrl.search which is not filled in because e.preventDefault() was called in paste handler.

To fix this we could add timeout before calling ctrl.select from paste handler, and remove e.preventDefault() from it something like this:

```javascript
ctrl.searchInput.on('paste', function (e) {
    var data = e.originalEvent.clipboardData.getData('text/plain');
    if (data && data.length > 0 && ctrl.taggingTokens.isActivated && ctrl.tagging.fct) {
        var items = data.split(ctrl.taggingTokens.tokens[0]); // split by first token only
        if (items && items.length > 0) {
            $timeout(function () {
                angular.forEach(items, function (item) {
                    var newItem = ctrl.tagging.fct(item);
                    if (newItem) {
                        ctrl.select(newItem, true);
                    }
                });
            });
            e.stopPropagation();
        }
    }
});
```

**Pull request closed without merging**
