### PR TITLE
fix accessing clipboardData in firefox

### PR DESCRIPTION
**Pull request by shali3**
in firefox you need to access e.clipboardData directly

### CODE REVIEW

**Comment by aaronroberson** [comment]
Please confirm fix in v0.14.7 and close this issue.

**Comment by shali3** [comment]
will do. Thanks!

**Comment by shali3** [comment]
It looks like it's working. But I had to download the version manually. why isn't it working nicly with bower?

**Comment by aaronroberson** [comment]
I don't manage the bower lib and can't publish to it. I can only publish to npm at this time.

**Comment by wesleycho** [comment]
Closing as already addressed.

**Pull request closed without merging**
