### PR TITLE
fix(dropdown): cross browser dropdown position

### PR DESCRIPTION
**Pull request by dimirc**
To avoid incorrect dropdown position

Wrong [Demo](http://plnkr.co/edit/oZCudVaPNc42B7hLYB7j?p=preview)

Corrected [Demo](http://plnkr.co/edit/vElyF6gmKYXA6jiM1K1k?p=preview)

*To reproduce, scroll down to red field*

### CODE REVIEW

**Comment by ramdog** [comment]
Hey, nice work.  Indeed this looks good in the case where the dropdown has room below:
image


However, it seems the case where the dropdown is opening above, this is still an issue (to reproduce, scroll down so that the red field is just above the bottom then type in `admin2`):
image

**Comment by dimirc** [comment]
@ramdog I cannot reproduce it. I just scrolled until red field is at bottom and then tried to open dropdown but I see it showing above correctly. In what browser did your tried? Can you explain me better how to reproduce it?

Chrome
image

Firefox
image

**Comment by ramdog** [comment]
Hey @dimirc, it does open correctly, but from your screenshots it looks like you may have missed the last step in testing.  

1.  Do exactly what you did (scroll down just enough to force the dropdown to open up).
2.  Then type out `admin2` - the whole thing.  Notice the **`Admin2`** option is indeed selected but still floating way up. Instead, it should be just above the search input.

**Comment by dimirc** [comment]
@ramdog got it. Pls recheck the corrected demo and it should be working correctly now

**Comment by ramdog** [comment]
Looks great, nice work!
:+1:

**Comment by estevaolucas** [comment]
Nice. It's working.

**Comment by GitHubUserNameX** [comment]
Nice work. Is their also the intention to make this work in the directions left and right?

**Pull request merged**
