### PR TITLE
enhance multiple accessibility

### PR DESCRIPTION
**Pull request by 0xF013**
make voiceover or chromevox speak the current item (multiple or not).

### CODE REVIEW

**Comment by lindenthal** [comment]
Hi guys,

**Comment by wesleycho** [comment]
Can you rebase this against current `master`?

**Comment by hboylan** [comment]
It looks like this update only affects the select2 templates. Can the same be attributes be applied to the bootstrap/selectize for consistency?

**Comment by user378230** [comment]
@hboylan this PR looks like it might be dead, you may find it more timely to submit a replacement :smile:

**Comment by Jefiozie** [comment]
Closing it down as it is a old issue. Please create new issue if this is still a bug/ problem.

Thanks.

**Pull request closed without merging**
