### PR TITLE
Add taggingLabel for single and multiple select

### PR DESCRIPTION
**Pull request by viniciusdacal**
issue #938

### CODE REVIEW

**Comment by LeleDev** [comment]
Please merge this one soon...

**Comment by brianfeister** [comment]
Sorry but there are so many issues to backtrack, can you post a Plunkr demonstrating the bug so I can verify this fixes it?  Maybe there already is a demo of the problem but I can't find it and would like to have it documented here for future reference. Thanks @viniciusdacal

**Comment by viniciusdacal** [comment]
In this first Plunkr you can see the error. 
http://plnkr.co/edit/7tPA05od2FUCbZRqj8UY?p=preview
Just try to add a new item in the single select, It should show a label, but nothing happens.
In the multiple select, try to type "Adam" and you will get the follow error:
`Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: person in $select.items track by person.name, Duplicate key: Adam`

On this follow Plunkr, I just add my current version of select.js with the fixes.
http://plnkr.co/edit/bG7yvD8YotzwexvSHti0?p=preview

Thanks @brianfeister

**Comment by vladichimescu** [comment]
@brianfeister, as this pull request fixes a critical function (taging on single select), can you allocate the time for merging it to master ?

**Comment by manichandra** [comment]
+1

**Comment by kshutkin** [comment]
#1006

**Comment by viniciusdacal** [comment]
@brianfeister any news about it?

**Comment by yaojingguo** [comment]
+1

**Comment by MartinNuc** [comment]
+1

**Comment by eranimo** [comment]
+1

**Comment by rodrigogoncalves** [comment]
+1

**Comment by eric-norcross** [comment]
+1

**Comment by Nekmo** [comment]
+1

**Comment by valloq** [comment]
+1

**Comment by cojack** [comment]
Anything new?

**Comment by bwilson-ux** [comment]
+1

**Comment by fferraris** [comment]
+1

**Comment by mgombocz** [comment]
+1

**Comment by capic** [comment]
:+1:

**Comment by bryanstetson** [comment]
+1

**Comment by isery** [comment]
+1

**Comment by rodrigogoncalves** [comment]
Is there anything I could do to help having this PR merged?

**Comment by neoned** [comment]
any news about it?

**Comment by jaymanned** [comment]
+1

**Comment by jkevingutierrez** [comment]
+1

**Comment by jkevingutierrez** [comment]
Any news ?

**Comment by MartinNuc** [comment]
We forked viniciusdacal's version and use it for like 6 months already.

**Comment by karlr42** [comment]
As was mentioned [here](https://github.com/angular-ui/ui-select/issues/938#issuecomment-157988675) for me the easiest workaround was just to use a regular multiple with tagging and set limit="1".

**Comment by performatric** [comment]
this works in angular ^1.4?

**Comment by performatric** [comment]
@viniciusdacal your fork works in angular ^1.4?

**Comment by alekstrust** [comment]
Any news? It's been almost a year :(

**Comment by wesleycho** [comment]
This needs rebasing.

**Comment by viniciusdacal** [comment]
thanks @wesleycho. 
I will work on this.

**Comment by viniciusdacal** [comment]
@wesleycho  updated.

**Comment by viniciusdacal** [comment]
any news about the revision?

**Comment by user378230** [comment]
There are still conflicts apparently, can you rebase again? 
Are there no associated tests?

**Comment by viniciusdacal** [comment]
@user378230 when I rebase my branch last time, I got the current code and added the changes again. so, this code has all changes from the day I rebased.

**Comment by jpkleemans** [comment]
+1

**Comment by user378230** [comment]
> @user378230 when I rebase my branch last time, I got the current code and added the changes again. so, this code has all changes from the day I rebased.

Thats fine, just still need to make sure no changes are dropped prior to commit of copy-paste. 

This still needs test(s), rebasing, example updating & squashing though. Once that is done, I'll merge. 

Thanks for your patience and hard work! :+1:

**Comment by Teegrounet** [comment]
I think you should add : ctrl.taggingLabel = '(new)'; in controller 
Without this, if taggingLabel attribute doesn't exist ctrl.taggingLabel is not initialized and newItem = ctrl.search+' '+ctrl.taggingLabel; -> ctrl.search+' '+ undefined

There is a problem with the watchCollection : when the watch is throw, the tagging element is removed -> use a refreshDelay="500" to see

**Pull request closed without merging**
