### PR TITLE
fix minimum-input-length with refresh-delay #1898

### PR DESCRIPTION
**Pull request by DaniVarga**
See #1898 
Example: http://plnkr.co/edit/A2LZVSO6X8xYYaYlaDos?p=preview

### CODE REVIEW

**Comment by Jefiozie** [comment]
Hi @DaniVarga , Thanks for the PR. Could you have a look again at it? 

- Think the NPM debug log can be removed

- Can you build some tests around it?

- think your editor has done something with indention could you fix it? 

Thanks

**Comment by DaniVarga** [comment]
Hi @Jefiozie,
> - Think the NPM debug log can be removed

The npm-debug.log is inside your repo. I have removed it from mine. Should i add a .gitignore rule?

> - think your editor has done something with indention could you fix it?

Indention looks fine to me. My editor just removed some trailing spaces: [Line 42](https://github.com/angular-ui/ui-select/blob/3642a1d6ec7cc7bc2a6dc31b745ad402da9ff02b/src/uiSelectChoicesDirective.js#L42), [Line 53](https://github.com/angular-ui/ui-select/blob/3642a1d6ec7cc7bc2a6dc31b745ad402da9ff02b/src/uiSelectChoicesDirective.js#L53), [Line 56](https://github.com/angular-ui/ui-select/blob/3642a1d6ec7cc7bc2a6dc31b745ad402da9ff02b/src/uiSelectChoicesDirective.js#L56) and [Line 50](https://github.com/angular-ui/ui-select/blob/3642a1d6ec7cc7bc2a6dc31b745ad402da9ff02b/src/uiSelectChoicesDirective.js#L50). This behavior is defined in your [.editorconfig](https://github.com/angular-ui/ui-select/blob/3642a1d6ec7cc7bc2a6dc31b745ad402da9ff02b/.editorconfig#L9) 

> - Can you build some tests around it?

I'll try

Thank you

**Comment by DaniVarga** [comment]
I dont know why the Tests are failing in Travis.
On my local machine everything is working fine.

> INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Firefox
INFO [launcher]: Starting browser Chrome
INFO [Chrome 56.0.2924 (Windows 10 0.0.0)]: Connected on socket vS7cylZ9ZljV6Fgiabub with id 88188217
Chrome 56.0.2924 (Windows 10 0.0.0): Executed 208 of 208 SUCCESS (5.517 secs / 5.499 secs)
Firefox 51.0.0 (Windows 10 0.0.0): Executed 208 of 208 SUCCESS (10.002 secs / 9.961 secs)
TOTAL: 416 SUCCESS

Can you have a look at it?

Tanks

**Comment by Jefiozie** [comment]
I hope I find the time later this week.

**Comment by DaniVarga** [comment]
Thank you.
It looks like something is wrong with Travis. Test 59 - 62 are failing in every build even in other PRs 
PR #1906 ([Travis](https://travis-ci.org/angular-ui/ui-select/builds/199535223)) and PR #1908 ([Travis](https://travis-ci.org/angular-ui/ui-select/builds/199650983))

**Comment by Jefiozie** [comment]
So i did some local test. Don't see why travis throws these errors. But i'm getting errors local. Could you  double check on your side if there are no errors? Thanks.

**Comment by DaniVarga** [comment]
Can't reproduce.
I've added Firefox and Chrome to my local karma.conf.js. Tests are passing.
image

**Comment by Jefiozie** [comment]
Can you share your node and npm version? Thanks.

**Comment by Jefiozie** [comment]
Hi @DaniVarga I think i have found the reason for the failing unit tests. Waiting for some comments why things have changed after this we can probably rebase your PR and the unit test problem will be resolved.

Thanks.

**Comment by Jefiozie** [comment]
HI @DaniVarga , I have merged my PR could you rebase to the master?
Thanks.

**Comment by DaniVarga** [comment]
Done :)

**Comment by Jefiozie** [comment]
Thanks, could you maybe adjust your tests? See [example](https://github.com/angular-ui/ui-select/blob/master/test/select.spec.js#L3190) I would like to get rid of all the `compileTemplate `and only use the function's as in the example.

**Comment by Jefiozie** [comment]
Any updates on this issue? 

Thanks

**Comment by Jefiozie** [comment]
Any updates on this issue?  @DaniVarga would like to get this merged 👍 

Thanks

**Comment by Jefiozie** [comment]
Merged but at some point we need to remove the `compileTemplate `and change it to `createUiSelect `or `createUiSelectMultiple`

**Pull request merged**
