### PR TITLE
Add scope event for refresh

### PR DESCRIPTION
**Pull request by asleepwalker**

### CODE REVIEW

**Comment by aaronroberson** [comment]
Please remove dist files from PR :D

**Comment by asleepwalker** [comment]
Done.

**Comment by user378230** [comment]
@asleepwalker can you update the [wiki](https://github.com/angular-ui/ui-select/wiki/ui-select) please?

**Comment by asleepwalker** [comment]
@user378230 of course, but where I should write about it? This pull request was not about adding callbacks like existing `onSelect` and `onRemove`, but only broadcasting an event.

There are similar scope events here:
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L114
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L391
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L420
and they are not documented in the wiki.

**Comment by user378230** [comment]
@asleepwalker A sorry I saw the _Events_ heading a thought they were scope events. 

Feel free to add a section _Scope Events_ to the ui select wiki page (the one I linked previously).

**Pull request merged**
