### PR TITLE
Fix error in multiple choice select

### PR DESCRIPTION
**Pull request by lbolla**
`ngModel.$viewValue` can be null on multiple choice select and "$on('uis:select')" below can fail if so.

### CODE REVIEW

**Comment by wesleycho** [comment]
This needs changes to `dist` undone and rebasing.

**Comment by lbolla** [comment]
Should I not have changed files in `dist/`? I think they get rebuild when running `gulp test`, anyway.

**Comment by lbolla** [comment]
By the way, strangely enough `gulp test` does not fail on my machine.

**Comment by wesleycho** [comment]
The changes to `dist` should never be committed - part of the problem is the whole release process with the library I believe, but until that is addressed to be easier on users, this must be followed.

**Comment by wesleycho** [comment]
As to the failures, please rebase off of current `master` after removing the changes to `dist`

**Comment by user378230** [comment]
Isn't this superseded by #1529? (Which appears to have a better fix for the issue)

**Comment by wesleycho** [comment]
Could be - I just have been doing basic triaging yesterday and today, so you're probably in a better position to judge than me.

**Comment by user378230** [comment]
No problem. Any help is good help! :smile: 

I'm going to close as looks to be the same as #1529

**Pull request closed without merging**
