### PR TITLE
feat(choices): allow to set default dropdown position

### PR DESCRIPTION
**Pull request by dimirc**
We should be able to set dropdown position explicitly so I added a new attribute called `position` for the `<ui-select-choices>` tag, that will accept 3 values: *up*, *down* and *auto*

Sometimes we might not want the dropdown to go automatically up even when there isn't enough space, so now we can force position to always go to an specific direction.

Also you can specify globally at `uiSelectConfig` using `dropdownPosition`

Demo [plunker](http://plnkr.co/edit/J8plv8vnnrzFV61Pkpls?p=preview)

### CODE REVIEW

**Comment by isimonov** [comment]
Thanks a lot! My example works correctly http://plnkr.co/edit/Tzcp1q2WV7HZCp5meftC?p=preview

**Comment by karptonite** [comment]
This is actually not working properly for me.
http://plnkr.co/edit/NuSM3OfJUgbxCRYoln8z?p=preview
The role selector is set to position="true" and the select options go down at first, but then reverses if you type a letter, the delete it.
http://quick.as/wy2mc3zva

**Comment by dimirc** [comment]
@karptonite I found the bug and will push a new patch release today

**Comment by karptonite** [comment]
@dimirc Thanks! Your work on this is certainly appreciated!

**Comment by dimirc** [comment]
@karptonite v0.13.1 released and now your issue should be fixed. Check updated demo http://plnkr.co/edit/H6ZSPuZ6qnEEJAF4dFrA?p=preview

**Pull request merged**
