### PR TITLE
Fix broken bootstrap css styles

### PR DESCRIPTION
**Pull request by BP18**
Fix for issue #578

### CODE REVIEW

**Comment by ansonkao** [comment]
+1, please merge this in!

**Comment by ansonkao** [comment]
FYI - got impatient and tried doing my own build using this patch - but it didn't work! Bootstrap single select till looks terrible

**Comment by BP18** [comment]
Here's the demo Plunker with the changes from this pull request applied:
http://plnkr.co/edit/AToz9yJ8cQUv90hiSQpH?p=preview

Looks better to me... what "still looks terrible"?

**Comment by ansonkao** [comment]
I think I may have been using some maligned concoction of bower package that messed with my results - my apologies, please ignore my complaint.

**Comment by just-boris** [comment]
+1 appreciate this

**Comment by Kerumen** [comment]
:+1:

**Comment by BP18** [comment]
Thanks!

**Pull request merged**
