### PR TITLE
Fixed #850 Where Multiple Attribute Prevents Proper Required Validation

### LINKED ISSUE #850: required tag
Is it possible to set a required tag for this control? I am not getting a prompt when the required tag is set and it is embedded in a form element. Thanks.

### PR DESCRIPTION
**Pull request by kmccullough**
Please note that some of this code does not appear to be mine. I can only assume someone forgot to build.

### CODE REVIEW

**Comment by user378230** [comment]
Whoops that was probably me, sorry :flushed: 

Also, wouldn't it make more sense to override `ngModel.$isEmpty` in `uiSelectMultipleDirective` rather than checking `attrs.multiple` or am I missing something?

**Comment by kmccullough** [comment]
@user378230 It might make sense to do it there, and I can move it there if I need to, but I figured this was an OK place to put it, since it actually covers the $isEmpty for both multiple and non-multiple selects at runtime. This also allows the multiple attribute to be added/removed at runtime (in this context; I'm not sure if the rest of the control supports it).

**Comment by aaronroberson** [comment]
@kmccullough Can you also remove the dist/ files and rebase to squash these commits?

**Comment by kmccullough** [comment]
Also? In addition to what?

**Comment by aaronroberson** [comment]
Sorry, I was referring to @user378230's comment and if the two have you have come to a resolution?

**Comment by kmccullough** [comment]
Short of him responding, I suppose I can just move it since the default $isEmpty should cover that case. I'll try to have this done by end of day if @user378230 doesn't respond.

**Comment by user378230** [comment]
>...since it actually covers the $isEmpty for both multiple and non-multiple selects at runtime
I think single selection should be covered by the default $isEmpty check in angular. (https://github.com/angular/angular.js/blob/f1aea54a9b4ceaf13676a4e7b74bf0de718cd6a4/src/ng/directive/ngModel.js#L320)
> This also allows the multiple attribute to be added/removed at runtime (in this context; I'm not sure if the rest of the control supports it).
I don't think it does

I mean its no big deal... its only one or two lines I think it just makes more sense being in the multiple directive. :smile:

**Comment by kmccullough** [comment]
@user378230 @aaronroberson 
Made the requested changes and opened an actual branch https://github.com/angular-ui/ui-select/pull/1492

**Pull request closed without merging**
