### PR TITLE
Issue #148 - Add up direction to dropdown rendering.

### PR DESCRIPTION
**Pull request by JeromeLam**
This addresses issue #148, which relates to how the dropdown displays in the event there isn't enough space to render it fully.  An up direction has been added.

I verified the change against demo.html, demo-multi-select.html and the three theme html files.

### CODE REVIEW

**Comment by gitnik** [comment]
big :+1: for getting this in

**Comment by brianfeister** [comment]
Thanks @JeromeLam, I'll try to take a look soon.

**Comment by cyrilf** [comment]
Thanks @JeromeLam for this PR :sparkles: 
Hope it will be merge soon! :+1:

**Comment by brianfeister** [comment]
Thanks @JeromeLam

**Comment by Keirua** [comment]
:+1: Great !

**Comment by LeleDev** [comment]
how to disable up direction?

**Comment by igorlino** [comment]
+1

how to disable up direction? On some circumstances its doing something wrong.

**Comment by jpdesigndev** [comment]
This seems to be breaking for me. Perhaps it is for you all too?

The searchInput element is not focused, so opening the dropdown, and beginning to type doesn't work.

The `$timeout` function seems to be missing a call to now `focus()` the search input once it has been given the new display property.

```
$select.searchInput[0].focus();
```

**Comment by brianfeister** [comment]
@JeromeLam would love to get some help from you on this feature.  There are a number of bugs that seem to have come out of this feature #977, #990, #989, #976, #973.

**Comment by amrsh** [comment]
+1; [PR for 989] (https://github.com/angular-ui/ui-select/pull/989) fixes my issue.

**Comment by Flightfreak** [comment]
Experiencing the same problem. Even when bottom space available is more then top, it still takes a top position.

**Comment by igorlino** [comment]
Restating what I wrote in https://github.com/angular-ui/ui-select/issues/977#issuecomment-119199767.

From usability perspective, its really annoying not to control the direction where things appear.

With the buggy implementation, the version, as it, makes the latest version of ui-select unusable.

The PR #989 fixes the issue of inconsistent behaviour (at least in my design). Although I personally would like to have it configurable.

If this does not get fixed, its better to revert this feature.

**Comment by LeleDev** [comment]
@igorlino  Totally agree

**Comment by ramdog** [comment]
Agree with @igorlino.  I updated to the latest version to get the benefit of some other bug fixes I was facing.  While those other bugs indeed have been fixed (nice!), this has made the select unusable for my project.  It seems that when it's automatically showing the options above and you are using the multiselect search, the options don't really drop into place above the input nicely.  See this screenshot, the blue highlighted items should be just _above_ the input, not floating way up there like that:
image

Would be great if the "opens-up" thing was an option that could be configured __off__.

**Comment by ManuelPutallaz** [comment]
+1

**Comment by evillemez** [comment]
Yeah, this kinda hurts... also updated for other bug fixes, but now this.  I agree that if there isn't an option to disable it, it should probably be reverted.

**Comment by oshai** [comment]
+1 @evillemez

**Comment by tandrianoff** [comment]
I'm experiencing the same issue as @ramdog and it has made this unusable for me.

**Comment by LeleDev** [comment]
ui-select is dead in a broken, inusable state... great, really

**Comment by fferraris** [comment]
it's not anymore usable, please fix  :+1:

**Comment by IsmiKin** [comment]
Yes... please fix it :smile_cat:

**Comment by dimirc** [comment]
@ramdog can you setup a plunker to reproduce this and try solving asap?

**Comment by ramdog** [comment]
Hey @dimirc - the issue that @igorlino references has an existing one showing the issue:
https://github.com/angular-ui/ui-select/issues/977#issue-83383891 

Here it is:
http://plnkr.co/edit/oZCudVaPNc42B7hLYB7j?p=preview

#### Steps to reproduce
1.  Scroll down to the red field
2.  Start typing `admin2`

Note that the selection remains "floated" above.

**Comment by dimirc** [comment]
@ramdog take a look https://github.com/angular-ui/ui-select/pull/1212 
Thanks for the demo!

**Pull request merged**
