### PR TITLE
Fix tolerance for null or undefined values

### PR DESCRIPTION
**Pull request by homerjam**
Re-pull of #1035

### CODE REVIEW

**Comment by user378230** [comment]
Was this causing an actual issue? (Thinking in terms of if we can add a test for this somehow..)

**Comment by homerjam** [comment]
I did this a while ago but yes I believe it was causing the directive to break. I think a test would just need to give a null/undefined value for the model.

**Comment by user378230** [comment]
@homerjam can you add one and then I can merge in? It's best for them to be part of the same commit, ideally.

**Comment by homerjam** [comment]
Sure. I'll definitely give it a go

**Comment by user378230** [comment]
@homerjam just to confirm, these test fail without your change right?

**Comment by wesleycho** [comment]
Those tests currently pass without the changeset from the PR.

**Comment by homerjam** [comment]
Ah yes I meant to to say. I think this fix may have been to make sure the
placeholder text appeared on a null/undefined value (or something like
that, have been meaning to check). I can't recall now unfortunately. Would
seem its unnecessary now though.

**Comment by user378230** [comment]
Will close for now, it looks a bit silly admittedly but there's no need to introduce unnecessary change at the risk of breaking something else. Maybe that section will refactored at some point in the future, anyway. 

If anyone finds a need for this change please update with details and we can look at reopening this.

**Pull request closed without merging**
