### PR TITLE
fix(bootstrap): allow-clear style

### PR DESCRIPTION
**Pull request by dimirc**
- [x] Fix Firefox alignment
- [x] Clicking the X icon on Firefox isn't working

Demo [plunker](http://plnkr.co/edit/vtOWB1y2esheyryeq1aO?p=preview)

### CODE REVIEW

**Comment by starf** [comment]
Thanks for the fix.
For the love of god, merge this.
It probably deserves a release on it's own.

**Comment by dimirc** [comment]
>Have you checked in firefox ? It seems that the clear button is still below the drop down, however now, it's on the right side.

As @gzsombor [reported](https://github.com/angular-ui/ui-select/issues/578#issuecomment-74513674), there's an issue still with firefox

image

**Comment by dimirc** [comment]
Alignment on Firefox is fixed with last commit.  Updated [plunker](http://plnkr.co/edit/2SlTvP6tNEdYzMm5hyRW?p=preview)

Now a new problem in firefox is that clicking on the X icon isnt working. I suspect it might be something similar as https://github.com/angular-ui/ui-select/pull/196

**Comment by dimirc** [comment]
Clicking on X icon solved on Firefox. Updated [plunker](http://plnkr.co/edit/vtOWB1y2esheyryeq1aO?p=preview)

**Comment by abobwhite** [comment]
@dimirc Thanks!
@starf Couldn't have said it better myself!

**Comment by khalilst** [comment]
I used allowClear=true in js and allow-clear in html. None of them works. Any idea?
I'm using select2 latest version [4.0.3].

**Pull request merged**
