### PR TITLE
fix(focus): prevent focus stealing when clicking on other ui-select element

### LINKED ISSUE #253: Search input focus not switching between two select dropdowns
There's a bug when you have two select dropdowns with search, and you open one dropdown but before hitting enter or clicking a selection, you click the other dropdown and start typing, the text focus is still on the first dropdown.

Try in this plunkr:
http://plnkr.co/edit/wicNNsEWN3VC05PtlEKx?p=preview

The first dropdown closes when clicking outside, but the text focus is not lost, nor is the focus shifted to the second dropdown

### LINKED ISSUE #283: Focus stealing
In some case selector widgets may stuck into "focus stealing" mode. I.e. When trying to select another field in form (with mouse) ui-select field keeps stealing focus back (so attempt to select another field and type text there ends up typing in ui-select field).

Noticed with bootstrap theme, didn't yet figure steps required to trigger bug.

### LINKED ISSUE #598: Click out is focusing again the input
Since #286 tab works fine, but when using click there is still a bug

### LINKED ISSUE #646: Can't select normal input after opening ui-select
I have a form made up of normal inputs and ui-selects.

If a user clicks on a ui-select to open and does not select anything, and then they click on a normal input to focus it, the input is highlighted and then immediately unselected.

Example: Click on a select and then click on the input at the top.
http://plnkr.co/edit/0FfN8es9ssJkd17elBxJ?p=preview

ui-select-bug

### PR DESCRIPTION
**Pull request by dimirc**
- [x] Fix focus stealing when ui-select is open and clicking on other ui-select

Not working [Plunker](http://plnkr.co/edit/o7JC4bFWIf0KpcnzxGIQ?p=preview)
Fixed [Plunker](http://plnkr.co/edit/mLIvTBnL8voBLekPayQE?p=preview)

- [x] Fix focus stealing when ui-select is open and clicking on other inputs (#646)

Not working [Plunker](http://plnkr.co/edit/MQ1VuldDLsm6GDNPMEXU?p=preview)
Fixed [Plunker](http://plnkr.co/edit/uvfqngiOclpE47fvXHvh?p=preview)

Fixes #283 , Fixes #253, Fixes #598, Fixes #646

### CODE REVIEW

**Comment by BP18** [comment]
I don't think this fixes #646. If I open the "Fixed Plunker" and add a regular text input box at the top, I can still reproduce the problem demonstrated in the video in #646.

**Comment by dimirc** [comment]
@BP18 you are right, I just created this new [plunker](http://plnkr.co/edit/MQ1VuldDLsm6GDNPMEXU?p=preview) to reproduce the bug. 

Seams like this PR right now is only fixing the focus problem when clicking on other ui-select controls. I'll need to look on this other issue too so that we could resolve it also on this PR

**Comment by dimirc** [comment]
@BP18 take a look now

**Comment by BP18** [comment]
Played around with the fixed Plunker and it looks good now. Thanks!

**Pull request merged**
