### PR TITLE
Don't hide input box when SearchEnable is false

### PR DESCRIPTION
**Pull request by cdjackson**
Fixes https://github.com/angular-ui/ui-select/issues/453

### CODE REVIEW

**Comment by dimirc** [comment]
Up and down key don't work

**Comment by cdjackson** [comment]
Thanks - I’ll take a look…

**Comment by cdjackson** [comment]
I've modified the concept slightly to allow the keys to work correctly. The problem was that by hiding the search box, we loose focus on the input. I've now changed this to instead add the 'ui-select-offscreen' class to the searchbox so that it still provides keyboard input, but is also hidden from the user.

I also added closing the select list if the list is open, and the user clicks on the match box again when in searchEnabled=false mode. Previously you had to click off the ui-select completely which seems wrong.

**Comment by wesleycho** [comment]
History needs to be cleaned up here - there should not be any merge commits. It may be better to open a new PR with clean history.

**Comment by cdjackson** [comment]
Squashed into a single commit.

**Pull request closed without merging**
