### PR TITLE
Do not overflow matched item out of select block

### PR DESCRIPTION
**Pull request by just-boris**
If selected value is so long, the select looks not nice. See the plunk: http://plnkr.co/edit/QtrdYP?p=preview

This css fixes it.

### CODE REVIEW

**Comment by just-boris** [comment]
FYI. Build has failed as well as other pull-requests because of some code, which already is in master.

**Comment by wesleycho** [comment]
This looks pretty straightforward.

**Comment by user378230** [comment]
This should probably be applied to the other templates too I think. Will merge for now.

**Comment by user378230** [comment]
Had to revert this in d7d26ca as it broke with the `allow-clear` button (pushed it out of the select)

**Pull request merged**
