### PR TITLE
Fix button in dropdown

### PR DESCRIPTION
**Pull request by alaingilbert**
Fix the case when you want a button in a dropdown.

**Expected behavior:** The page should not reload when the button is clicked
**Current behavior:** Page reload when button clicked

Bug introduced here: https://github.com/angular-ui/ui-select/pull/1295

Broken (current master): http://plnkr.co/edit/gkm4ymXQbgemCpUteATg?p=preview
Fixed: http://plnkr.co/edit/AJT0rL2OGQw2vV8mRdkN?p=preview

### CODE REVIEW

**Comment by user378230** [comment]
Does it need to be an anchor tag? Could we just use a styled `span`?

**Comment by alaingilbert** [comment]
I tried with a `span` and it actually change the styling a lot.
And he cell is not completely covered by the `cursor: pointer;`.
Here is an example with the `span`: http://plnkr.co/edit/vfYKkdWzxmgb3bPIZGxU?p=preview

**Comment by user378230** [comment]
There are some CSS selectors looking for anchor tag in src/common.css (I can't link to line on mobile) but look for `.ui-select-choices-row>a` can you try with reconfiguring them to spans? Thanks for your efforts so far 😃

**Comment by alaingilbert** [comment]
I have updated the previous plnkr with the updated code html/css:
http://plnkr.co/edit/vfYKkdWzxmgb3bPIZGxU?p=preview

**Comment by user378230** [comment]
Is ng-click attribute still required now? `span` doesn't have a default action we need to prevent (I don't think?)

**Comment by alaingilbert** [comment]
Good point.
I have updated the plnkr (http://plnkr.co/edit/vfYKkdWzxmgb3bPIZGxU?p=preview)

**Comment by alaingilbert** [comment]
Any update ?

**Pull request merged**
