### PR TITLE
Solves Append the list to body #41

### PR DESCRIPTION
**Pull request by dhaval-patel**
Created a layer at body level and appended dropdown to it. So it will not affect the height of actual control and it will also prevent mouse wheel after dropdown is opened.

### CODE REVIEW

**Comment by dmccown1500** [comment]
If this works well lets get in in!

**Comment by leipert** [comment]
@dhaval-patel Could you please add the changes to the corresponding files in the src folder instead of the dist file? We cannot see what you changed.

**Comment by amcdnl** [comment]
Please remove the dist folder and only submit the src changes.

**Comment by cmlenz** [comment]
#718 also implements this feature.

**Comment by dhaval-patel** [comment]
@amcdnl done !!

**Comment by dhaval-patel** [comment]
@cmlenz My solution has default as "Append to Body". But I can make it as your saying. It will be much better.

**Comment by leipert** [comment]
@dhaval-patel . No, please have a look at #718 for example. You should not have changes in the dist folder. The dist should not appear at all!
And the changes you made should be in the individual src files. We do not see what you changed. If you change the uiSelect directive, change uiSelectDirective.js.

If you want to test ui-select with your new feature you have to
```bash
$ npm install
$ gulp test
$ gulp build
```

If you do not have gulp installed globally, do it with `npm install -g gulp`

**Comment by dhaval-patel** [comment]
@leipert I don't see any individual files in my repo. My repo contains only select.js. May be you guys have changed your repo structure after I pulled.

**Comment by leipert** [comment]
Ah okay, I did not know. I am not a maintainer ;) Well hopefully one will come along and give some advice and either merge this PR or #718

**Comment by brianfeister** [comment]
@dhaval-patel there was a major structural change in v0.9.9 and your CSS indicates that your branched off at 0.9.4.  Sorry for the inconvenience but I can't see your changes with the current PR, you need to rebase current master onto your branch before I can review this.  Also, I don't think this will be merged because #718 seems to do the same thing and is already properly rebased.

**Pull request closed without merging**
