### PR TITLE
Bug fix - Search input isn't blocked 

### PR DESCRIPTION
**Pull request by nabilnaffar**
Scenario:
- multiple select
- search-enabled is set to false
- all items are selected
- user type something in search input

expected results:
input keys should be blocked, input search should stay clean

actual results:
keyboard keys are shown in input search

### CODE REVIEW

**Comment by aaronroberson** [comment]
@nabilnaffar Can you please remove the `dist/` files from the PR?

**Comment by nabilnaffar** [comment]
@aaronroberson sure!

**Comment by aaronroberson** [comment]
Thanks @nabilnaffar!

**Comment by chadfurman** [comment]
I feel like this was a bad PR @aaronroberson -- When I type something into the search box and it returns no results from my API call, I cannot hit the backspace button.  In fact, I can no longer hit _any_ button while I have the input focused.

**Comment by Jefiozie** [comment]
Added PR for reverting this maybe @nabilnaffar  can have a look at the comments and make a new PR.

**Comment by nabilnaffar** [comment]
@chadfurman can you specify the scenario that doesn't work + browser/OS? I'll try to reproduce it

**Comment by ohjames** [comment]
Is this the PR that broke release 0.19.5? I think this version should be pulled from bower etc. it is unusable for the reasons @chadfurman lists.

**Comment by lundens** [comment]
With the current dist, I get this behaviour:
http://plnkr.co/edit/yuyks6ddYFWw1gUhnmEP?p=preview

**Comment by aaronroberson** [comment]
Merged and published as 0.19.6. Unfortunately, NPM won't let me unpublish 0.19.5.

**Comment by rthrfrd** [comment]
For us 0.19.5 completely broke any multiple selects that have no options preset and rely on `refresh` to fetch the options after the user begins typing, as the user is unable to type anything at all.

**Comment by user378230** [comment]
The tag was missing from the `0.19.6` release for this revert so I've just pushed one to ensure bower is updated.

**Pull request merged**
