### PR TITLE
Auto-select an exact dropdown match when "free tagging" (no labels).

### PR DESCRIPTION
**Pull request by JeromeLam**
This addresses issue #640, which is specific to tagging. I verified the change against the basic demo.html file and there is no impact.

I feel that if a user typed an exact match and pressed Enter, the tag should still get created.  The user shouldn't be required to click on the selection in the dropdown.

### CODE REVIEW

**Comment by dimirc** [comment]
@JeromeLam could you add a test for this?

**Comment by JeromeLam** [comment]
@dimirc This is my first time writing tests, and I struggled all day trying to make it work.  Could you give me pointers?

In [createUiSelectMultiple()](https://github.com/angular-ui/ui-select/blob/master/test/select.spec.js#L1178), I added ```if (attrs.tagginglabel !== undefined) { attrsHtml += ' tagging-label="' + attrs.tagginglabel + '"'; }```.  After that, I duplicated the [following test](https://github.com/angular-ui/ui-select/blob/master/test/select.spec.js#L1689) in hopes of modifying it without much success.  I figure that just by adding *tagginglabel: "false"* to the options of *createUiSelectMultiple()* would make it work, but the test fails.

Can you advise me on how to make it work?  Your expertise is greatly appreciated!

**Comment by dimirc** [comment]
@JeromeLam just to reconfirm that what I understood you is ok, when a user types something that has an exact match, then the match should be selected? is this what you are trying to do or something different?

**Comment by JeromeLam** [comment]
@dimirc That's correct.  In free-tagging mode with no labels, if you typed an exact match in the dropdown, the exact match wouldn't be highlighted.  If you pressed Enter to commit the exact match being typed (not selecting it from the dropdown using the mouse), it didn't get added without the fix in this PR.  You can always refer to #640 for steps to reproduce the odd behavior (at least to me).

**Comment by wesleycho** [comment]
Closing due to what appears to be strange history.

The code seems to have changed since then - for example, the beginning to the file in this PR is present in src/common.js. Feel free to open a new PR on top of current `master`.

**Pull request closed without merging**
