### PR TITLE
Allow discard tag when tagging function returns null

### PR DESCRIPTION
**Pull request by alexcrown**
Issue #485

### CODE REVIEW

**Comment by dimirc** [comment]
LGTM

**Comment by dimirc** [comment]
@alexcrown can you squash it to one commit?

**Comment by LeleDev** [comment]
Eagerly waiting for this to be merged

**Comment by dimirc** [comment]
Rebased and Merged with https://github.com/angular-ui/ui-select/pull/678

Thanks @alexcrown!

**Pull request closed without merging**
