### PR TITLE
Buttons should always have an attribute type with the value button.

### PR DESCRIPTION
**Pull request by realityking**
This prevents submitting a form that contains a UI Select.

### CODE REVIEW

**Comment by realityking** [comment]
Any news on this? We currently have to manaully patch UI Select, which is rather annoying.

**Comment by erikverheij** [comment]
+1

**Comment by gerardp** [comment]
+1

**Comment by wtilton** [comment]
+1

**Comment by realityking** [comment]
Fixed with 1e25650d78242abfe54bfd1c50d4997485729b8c

Sorry, I had missed #503.

**Pull request closed without merging**
