### PR TITLE
Added the header click event

### PR DESCRIPTION
**Pull request by prakashn27**
After performing groupby for the dropdown customer can select all the elements in the grouped list by clicking on the header.

### CODE REVIEW

**Comment by cdjackson** [comment]
Note that this won't be able to be merged. Firstly, there is a merge conflict, but secondly, I guess you have reformatted the source files so it shows every line changed and is therefore not possible to merge.

**Comment by knulan** [comment]
@prakashn27 thanks for your code, I want to use it on my project, so can you please describe how this header click event is working (do I need to add some extra attributes to my ui-select)?

**Comment by prakashn27** [comment]
@knulan : i just added a javascript function when the groups are categorised. and then i added an event for that header click to enable all the elements within the category. Please see my [repo](https://github.com/prakashn27/ui-select) for detailed information. :)

**Comment by knulan** [comment]
@prakashn27 thanks for reply

**Comment by wesleycho** [comment]
Closing due to modification to incorrect file and being impossible to properly review.

Feel free to open a new PR against current `master` with changes to non-dist files.

**Pull request closed without merging**
