### PR TITLE
Allow sorting of multiple select

### PR DESCRIPTION
**Pull request by homerjam**

### CODE REVIEW

**Comment by wmertens** [comment]
:beers: :tada: :+1::exclamation:

**Comment by dimirc** [comment]
@homerjam LGTM

Only quick issue that found was when dragging all the wat to the right, the index is pasted in the input
image

Btw, why not just `sortable` as attribute instead of `sort-enabled`?

**Comment by homerjam** [comment]
I'll try and fix that, I guess we can disable the input while dragging or
something.

I went for `sort-enabled` because it followed the other options more
closely I thought. I'm not wedded to either though. Anyone else have an
opinion on that? I can easily change my PR, so let me know.

**Comment by homerjam** [comment]
@dimirc I've resolved that problem you noted - I've also changed the attribute to `sortable`(think it does make more sense actually)

**Comment by dimirc** [comment]
Thanks @homerjam

**Comment by stevematyas** [comment]
Can anyone advise on the proper use of sortable="true"? Reference: #974

**Comment by cheesecase** [comment]
Hi, is there a documentation how to use the sorting (sortable="true") for multiple select?

More specifically, is there an option to change the sorting from horizontal to vertical without changing the code?

Thanks

**Pull request merged**
