### PR TITLE
make sure sortable classes are removed properly

### PR DESCRIPTION
**Pull request by homerjam**

### CODE REVIEW

**Comment by wesleycho** [comment]
Needs rebasing, but otherwise LGTM

**Comment by homerjam** [comment]
@wesleycho I have rebased now. Thanks for ploughing through all the PRs, great work!

**Comment by user378230** [comment]
You've just slightly borked the commit message now :stuck_out_tongue_closed_eyes: 

Can you fix? Is there a related issue for this?

**Comment by homerjam** [comment]
Oops :relaxed: 

No there's no issue - I just came across it and submitted the PR.

**Comment by wesleycho** [comment]
@user378230 what are your thoughts - I can merge this locally and alter the message before pushing up if it makes it easier.

**Comment by homerjam** [comment]
Sorry did I forget to fix this? Will make a note

**Comment by user378230** [comment]
LGTM now :+1: feel free to do it locally

**Pull request closed without merging**
