### PR TITLE
fix-#1499-error

### PR DESCRIPTION
**Pull request by tangfang**
fix-#1499-error

### CODE REVIEW

**Comment by tangfang** [comment]
when to merge pull request?

**Comment by user378230** [comment]
Hi, please see commit guidelines in [contributing doc](https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md#commit). If you can clean up the commit I will merge. 

Note that the comment `//fix-#1499-error.` is **not** required its why we use git in the first place :smile:

**Comment by wesleycho** [comment]
This may supercede #170.

**Comment by user378230** [comment]
This also needs a test, it probably got through because one currently doesn't exist for attribute usage of the directive.

**Comment by user378230** [comment]
Closing as superseded by #1555 as per https://github.com/angular-ui/ui-select/issues/1580#issuecomment-215276541

**Pull request closed without merging**
