### PR TITLE
add "group filter" feature

### PR DESCRIPTION
**Pull request by Vitaliy-Yarovuy**
i my case i need to change default order of groups.
In this realisation order can be set by array of groupName or function "groupsFilter" ( work like group-by)

### CODE REVIEW

**Comment by Vitaliy-Yarovuy** [comment]
resolve the same issues as #356

**Comment by brianfeister** [comment]
Can you please add an example somewhere in `/examples`?

**Comment by Vitaliy-Yarovuy** [comment]
done

**Comment by brianfeister** [comment]
Ah, your changes are in the `/dist` directory.  These files are only changed when we push a new release so we'll need to make sure there are no changes in `/dist`

**Comment by Vitaliy-Yarovuy** [comment]
but if i not change dist, the demo will not work,
so i need to revert changes in dist ?

**Comment by brianfeister** [comment]
Yup, it will work after we merge, I will build dist.  Sorry for the workflow, it's confusing, I agree and I know.

**Comment by brianfeister** [comment]
This was merged at #969

**Pull request closed without merging**
