### PR TITLE
Fix multiple select issue with single property binding and track by expression 

### PR DESCRIPTION
**Pull request by AntiFreez**
This fixes https://github.com/angular-ui/ui-select/issues/709

### CODE REVIEW

**Comment by brianfeister** [comment]
Thanks, need to take a look.

**Comment by brianfeister** [comment]
Sorry for the extremely late review but there is a disconnect here.  I'm hesitant to remove this because this directive is doing so many things it must be there for a reason.  Re-assigning to @dimirc as he's more likely to have prior knowledge about why the `$select.parserResult.trackByExp` was in there.

**Comment by ckniffen** [comment]
This is also a feature I need.

**Comment by rafasoares** [comment]
Any updates on this?

**Comment by AntiFreez** [comment]
Unfortunately, no.

**Comment by user378230** [comment]
Closing as something [similar](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectMultipleDirective.js#L119) appears to have made its way in to master

**Pull request closed without merging**
