### PR TITLE
add option to always show placeholder: `placeholderAlwaysVisible` to ui-select-match

### PR DESCRIPTION
**Pull request by ptgamr**
In tagging use case, it is useful sometime when you still want to display the placeholder even when something is selected.

For eg

### CODE REVIEW

**Comment by aaronroberson** [comment]
@ptgamr  We are not keen on adding a plethora of directive attributes to the components. I would love to see a PR that refactors the the directives away from having a million attributes and instead accepting a config object.

**Comment by wesleycho** [comment]
Changes to `dist` need to be undone, and this looks like it'd need tests.

**Comment by user378230** [comment]
This can probably be written as a separate directive:
```js
app.directive('placeholderAlwaysVisible', function() {
  return {
    require: 'uiSelect',
    link: function($scope, $element, attrs, $select) {     
      $select.getPlaceholder = function () {
        return $select.placeholder;
      }
    }
  }
});
```

**Comment by BojoDimov** [comment]
Hello, I have the same request, also tried making separate directive just as you shown before, but it doesn't seem to be workring.

Here is my controller
```javascript
.directive('alwaysShowPlaceholder', function () {
    return {
      restrict: 'A',
      require: 'uiSelect',
      link: function ($scope, $element, attrs, $select) {
        console.log($select);
        console.log($select.getPlaceholder);
        $select.getPlaceholder = function () {
          return $select.placeholder;
        }
      }
    };
  });
```
and html
```html
<ui-select ng-if="permissionGroup.inEditMode"
                   multiple
                   class="separate-rows"
                   theme="bootstrap"
                   always-show-placeholder
                   ng-model="permissionGroup.permissions">
          <ui-select-match >{{$item.displayText}}</ui-select-match>
          <ui-select-choices repeat="permission in PermissionArray | filter:$select.search">
            <div ng-bind-html="permission.displayText | highlight: $select.search"></div>
          </ui-select-choices>
        </ui-select>
```
and the resulting output is:

```javascript
Object {...}
undefined
```

which make me think  that we don't have access to the underlying functions or they are not initialized at that moment, so after they initialize they overwrite our implementation.
I would really appreciate if you would help me with that problem.

**Comment by user378230** [comment]
Plunkr? I suggest maybe also trying to adjust directive `priority`

**Comment by BojoDimov** [comment]
Thank you for the quick response, here is the plunkr with priority property set and also executed on post link stage:
[http://plnkr.co/edit/pe8v5ZeWXfloYfqE4AVd?p=preview](http://plnkr.co/edit/pe8v5ZeWXfloYfqE4AVd?p=preview)

**Comment by ptgamr** [comment]
`.getPlaceholder()` is defined in `uiSelectMultipleDirective`'s controller: `$selectMultiple`

So you can't override it in `uiSelectDirective`'s controller: `$select`

**Comment by ptgamr** [comment]
And because of this switching template logic: https://github.com/ptgamr/ui-select/blob/cb2c5611450ea5bf5fa806416c180af9273a2755/src/uiSelectDirective.js#L21 , it's not easy to override this behavior...

**Comment by ptgamr** [comment]
@user378230 I can suggest to move `getPlaceholder` to `$select`, so user can easily override the behavior if needed to.

I'm happy to update the PR if this way is the correct way to go.

**Comment by user378230** [comment]
@ptgamr that sounds like a good idea, can you update single select to use `getPlaceholder` (it should always return placeholder for single select but its good to allow users to override `getPlaceholder` for single select if they like.

**Pull request closed without merging**
