### PR TITLE
fix(resetSearchInput) multiple didn't clear after selecting

### LINKED ISSUE #1760: in multiple select mode, the search text is not cleared until you focus on the input again
### Bug description:
with multi select enabled, if you start typing in the input and select a choice, the text you searched in the input remains, even with uiSelectConfig.resetSearchInput = true, until you click/focus the search input again

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/cQJiIwW7zMZpYmm4NAhl?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5

UI-Select: 0.19.1

Bootstrap/Select2/Selectize CSS (if applicable): all

### PR DESCRIPTION
**Pull request by Jefiozie**
This will fix #1760 

Still I don't have any tests @user378230  any thoughts on this.
Did try some stuff but didn't succeed.

### CODE REVIEW

**Comment by Jefiozie** [comment]
Added some unit test to prevent problems in the future. 
Still don't know if this is the best way to validate the resetSearch function, would love to see some feedback :smile:

**Comment by user378230** [comment]
>1,226  test/select.spec.js
630 additions, 596 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

Did you intend to make that many changes? I've not pulled down to review yet just wondering if maybe you broke some whitespacing or something.

**Comment by Jefiozie** [comment]
@user378230 think I used auto format reverted the commit and added the new tests. These will check if the multiple ui-select is working with resetSearchInput.

**Comment by timelf123** [comment]
Thanks for the fix, this was driving me crazy. @aaronroberson any chance this can be merged and a new release cut?

**Comment by aaronroberson** [comment]
Merged. Will test to see if the travis hooks will update the version and publish to NPM.

**Comment by timelf123** [comment]
Travis didn't run:
```
Skipping a deployment with the script provider because this is not a tagged commit
Skipping a deployment with the npm provider because this is not a tagged commit
```

**Comment by Jefiozie** [comment]
@aaronroberson, thanks for merging this :smile:. I will update the wiki as the resetsearchinput is default false.

**Comment by aaronroberson** [comment]
Thanks @timelf123 and @Jefiozie! v0.19.3 is now available :D

**Comment by timelf123** [comment]
thanks @aaronroberson for the quick merge! can you `git tag 0.19.3 && git push --tags`?

**Comment by user378230** [comment]
We should really revert the default back to `true`

**Comment by aaronroberson** [comment]
@Jefiozie Can you create a PR to revert the default to `true`?

**Comment by Jefiozie** [comment]
@aaronroberson Sure no problem!

**Pull request merged**
