### PR TITLE
Cast other data types to string when highlighting

### PR DESCRIPTION
**Pull request by slawekkolodziej**
This PR fixes 'undefined is not a function' error, when you try to pass number through "highlight" filter, like here:

```
<div ng-bind-html="person.age | highlight: $select.search"></div> 
```

I looked for possibly related issues and I found these: #517 and #555

### CODE REVIEW

**Comment by cdjackson** [comment]
Possible duplicate of #1008

**Comment by slawekkolodziej** [comment]
Yup, it appears to be a duplicate. The only difference is that mine PR provides unit tests. Anyway, why don't you merge any of them to actually close the issue?

**Comment by cdjackson** [comment]
> Anyway, why don't you merge any of them to actually close the issue?

Because when I wrote this I was just trying to help the maintainers out by identifying duplicates with a view to tidying up the repository...
Now I have access to the repository with a view to refactoring it (see #1096 / #1108) and I'll add this there (#1134).

**Comment by slawekkolodziej** [comment]
Ahh I see! I assumed that this project was dead, but it definitely needed guys like you :+1:

**Comment by user378230** [comment]
#1402 merged so closing this.

**Pull request closed without merging**
