### PR TITLE
feat(limit): Change multi-select limit attr

### PR DESCRIPTION
**Pull request by cauld**
attr.limit should be an observable property so that it is
updatable after initialization

### CODE REVIEW

**Comment by cauld** [comment]
@aaronroberson it has been a while since you accepted this pull request and while I can see it has been merged into master the main dist file [still seems to have the old logic](https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L953). Any thoughts?

**Comment by aaronroberson** [comment]
I'll take a look!

**Comment by cauld** [comment]
@aaronroberson any luck tracking down the issue here?  Should I just submit a new pull request?

**Comment by aaronroberson** [comment]
Sorry, I recently started a new job at Nike and lost track of this one. @cauld, please create a new PR, that would streamline everything!

Thanks!

**Comment by cauld** [comment]
@aaronroberson no worries, just updated against the latest ui-select master and submitted a fresh pull request - https://github.com/angular-ui/ui-select/pull/1632.

**Comment by aaronroberson** [comment]
Perfect! Merged and will land in the next release!

**Pull request merged**
