### PR TITLE
Selectize - Add support for multiple selection

### LINKED ISSUE #295: No selectize theme multiple selection templates.

### PR DESCRIPTION
**Pull request by gustavohenke**
Closes #295

### CODE REVIEW

**Comment by ryanseaton** [comment]
👍

**Comment by eMerzh** [comment]
Thanks for this PR!
i'm really interested in this too as i just discover now that multiple selectize is not supported :/

**Comment by user378230** [comment]
Hopefully this doesn't go horribly wrong, thanks for your PR!

**Comment by JozefFlakus** [comment]
Repository needs updated dist folder

**Comment by Maximaximum** [comment]
Could please anyone update the dist folder?

**Pull request merged**
