### PR TITLE
refactor(commonjs): Added support for npm and commonjs

### PR DESCRIPTION
**Pull request by aaronroberson**
Added `ui.select` to module exports so that after installing via npm, the package can be required in the angular module dependency list such as:

angular.module('myApp', [require('angular-ui-select')]);

This is helpful for Browserify and Webpack.

### CODE REVIEW

**Comment by okhomenko** [comment]
+1

**Comment by eranimo** [comment]
:+1: Why wasn't this in before?

**Comment by gaui** [comment]
:+1:

**Comment by yukw777** [comment]
When will this be merged?

**Comment by bsideup** [comment]
:+1:

**Comment by ranjith19** [comment]
What is going on here?

**Comment by jashatton** [comment]
Please pull this in for release... doing hackery to get this working in my project can be avoided :) Thanks

**Comment by aaronroberson** [comment]
@dimirc Can you merge this PR in please?

**Pull request closed without merging**
