### PR TITLE
Update package name.  ui-select is a different project

### PR DESCRIPTION
**Pull request by MichaelJCole**
PR for #779

ui-select is a different project.  Updated the bower.json to use the same package name used when installing.

### CODE REVIEW

**Comment by titocr** [comment]
Holy heck. I pulled down ui-select and was confused for a while...

**Comment by alanmoo** [comment]
Just spent about 20 minutes lost  and confused because of this-- another vote to get this merged in.

**Comment by pedromarce** [comment]
Is there any reason why this is not merged?

Using brunch doesn't manage correctly dependencies due the difference between bower package and name defined in bower.json.

**Comment by wesleycho** [comment]
@user378230 might be worth running `curl https://patch-diff.githubusercontent.com/raw/angular-ui/ui-select/pull/812.patch | git am -3` on `master` and merging this in by manually resolving conflicts, squashing, and amending commit.

**Comment by user378230** [comment]
I don't know if its exactly what you were saying but I made a new PR (#1532) with the changes.

**Pull request closed without merging**
