### PR TITLE
fix for #890, #770

### PR DESCRIPTION
**Pull request by kshutkin**

### CODE REVIEW

**Comment by brianfeister** [comment]
Thanks for this, need to take a look.

**Comment by brianfeister** [comment]
Looks good, verified it works with this Plunkr: http://plnkr.co/edit/BZwOdzBKYedMkP9eMfo3?p=preview

**Comment by LeleDev** [comment]
Single select tagging seems to work, but the new tags doesn't show up among the others in the dropdown (as instead it does with multiple select)

**Comment by kshutkin** [comment]
I only fixed cases with tagging enabled but no labels (tagging-label="false").

**Comment by LeleDev** [comment]
OK... maybe this pull request could help with other cases? https://github.com/angular-ui/ui-select/pull/972

**Pull request merged**
