### PR TITLE
Add null check for regex results

### PR DESCRIPTION
**Pull request by vidakovic**
This is especially an issue when the directive is initialized on a page. The NPEs don't seem to break anything, but can't hurt to have this check in place.

### CODE REVIEW

**Comment by wesleycho** [comment]
Changes to dist need to be removed, and this needs to be squashed and rebased.

**Comment by syampolsky** [comment]
Any chance this can make it into the main branch soon? We are working on a project where we are not allowed to use non-official branched. This bug is killing our ui in prod.

**Comment by user378230** [comment]
@syampolsky please see labels and comments, this PR needs work before it can be merged. 

You're welcome to provide the work if you wish. 

Submit a new PR following CONTRIBUTING.md and I'll review and merge :smiley:

**Comment by user378230** [comment]
Closing due to age, probably already fixed.

**Pull request closed without merging**
