### PR TITLE
adding ability to disable a ui-select by setting its ancestor fieldset's disabled property

### PR DESCRIPTION
**Pull request by hmbl9r**
Disabling the root ui-select element works just fine, however something like this:

```html
<fieldset disabled>
    <ui-select ...>
        ...
    </ui-select>
</fieldset>
```

does not disable the ui-select control.

my changes to the code make this work.

### CODE REVIEW

**Comment by buraktamturk** [comment]
Any good reason for not merging this? This is definitely must have feature for a form element. I can control all of my form fields using fieldset except ui-select, in case I need to add same ng-disabled expression to ui-selects. Just why?

**Comment by portus84** [comment]
+1

**Comment by Sheeryada** [comment]
+1

**Comment by eugeneos** [comment]
+1

**Comment by AdamAxtmann** [comment]
This hasn't been merged because it's failing build tests. See #772 for a working fix.

**Comment by wesleycho** [comment]
Closing due to being superceded as mentioned in comments & due to age.

**Pull request closed without merging**
