### PR TITLE
Enable tagging without multi selection (see #597)

### PR DESCRIPTION
**Pull request by catchshyam**
This pull request addresses the issue https://github.com/angular-ui/ui-select/issues/597

I have included a sample demo code as well.

Thanks,

### CODE REVIEW

**Comment by brianfeister** [comment]
Thanks again for this @catchshyam.  Does this code work for you?  I've checked out your branch and tested locally.  The new item appears in the dropdown but it's not selectable via clicking it or hitting ENTER on the keyboard.

**Comment by brianfeister** [comment]
Nevermind.  Good to go. :+1:

**Comment by brianfeister** [comment]
Small side note, `on-select` isn't needed in the demo.  I will remove it for clarity.

**Comment by catchshyam** [comment]
Thanks @brianfeister . I will take the latest release into my project now.

**Pull request merged**
