### PR TITLE
Select first option no mater if it creates new tag or offers existing…

### PR DESCRIPTION
**Pull request by ilinsky**
…one. Addresses issue angular-ui/ui-select#1911

### CODE REVIEW

**Comment by ilinsky** [comment]
The 4 failing tests had been failing on master, they are not caused by the PR

**Comment by Jefiozie** [comment]
Hi @ilinsky I think i have found the reason for the failing unit tests. Waiting for some comments why things have changed after this we can probably rebase your PR and the unit test problem will be resolved.

Thanks.

**Comment by Jefiozie** [comment]
Hi @ilinsky sorry to keep you waiting. Please rebase your PR with the latest changes this should solve the build problem. After that I will have a look at your PR. 

Thanks.

**Comment by ilinsky** [comment]
Hi @Jefiozie It is done.

**Comment by Jefiozie** [comment]
Will this also solve #1887

**Comment by Jefiozie** [comment]
Any updates on this issue? 

Thanks

**Comment by ilinsky** [comment]
Nope, did not do any further checks. Can you elaborate on what need to be verified?

**Comment by Jefiozie** [comment]
In the [example](http://angular-ui.github.io/ui-select/demo-multiple-selection.html) you can see the `Disabling instead of removing selected items` will this still work on the changes you have made?

Next to this I would like some test also for the single select and multiple select if possible?
Thanks.

**Comment by ilinsky** [comment]
I tried examples and it is my understanding everything works.

**Comment by joaopgg** [comment]
Hi guys, any updates on this?

**Pull request merged**
