### PR TITLE
fix dragleave triggered on children

### PR DESCRIPTION
**Pull request by 0xF013**

### CODE REVIEW

**Comment by dimirc** [comment]
What error/issue was this causing?

**Comment by 0xF013** [comment]
@dimirc in some cases dragging a choice over another causes the whole drag process to cancel out. Should I prepare some examples?

**Comment by dimirc** [comment]
One example will be helpful to check this

**Comment by 0xF013** [comment]
@dimirc I am sorry, I might have introduced some side effects with this fix, mainly dragleave not being consistently fired. The problem I actually had got easily fixed with 
```
.select2-choices li * {
  pointer-events: none;
}
```
which was either not set or overwritten by some other css.

**Comment by dimirc** [comment]
Do you mean this commit should better be reverted then?

**Comment by 0xF013** [comment]
@dimirc yes please, I fixed the issue without looking into the cause

**Pull request merged**
