### PR TITLE
Added uiSelectFooter directive for bottom of list

### PR DESCRIPTION
**Pull request by csebold**
My humble attempt to contribute a footer directive for the bottom of the dropdown menu

### CODE REVIEW

**Comment by mrwarrens** [comment]
I would be a fan if this was merged.  My project has several cases where we need a footer, and at the moment we are hacking up a solution involving two sets of dom nodes inside of ui-select-choices and turn them on/off if it is the last element.

**Comment by csebold** [comment]
This is a feature of Select2, but I don't see it on ui-select's roadmap.  I'd love to see this rolled in, though.  If there's something I can do to make the code fit better, I'm willing to make it happen.

**Comment by joshrickert** [comment]
A header would be helpful as well... Same basic idea.

**Comment by shawn9273** [comment]
any idea on if/when this will be merged and released?

**Comment by dimirc** [comment]
@csebold I think that this might be good, but I see some trouble on each theme:

## Bootstrap
* footer is shown when the dropdown is closed
* footer is shown on top of the dropdown

image
image


## Selectize
* footer is shown when the dropdown is closed
* footer isn't shown when dropdown is open
image
image


## Select2
You mention:
>This is a feature of Select2, but I don't see it on ui-select's roadmap

But I dont see this on select2. I wanted to see if there were some select2 css clases to keep same style as right now seems like without any padding or default style

image

**Comment by plong0** [comment]
+1
anything more about having a ui-select-footer / ui-select-header?  I would really like this.

**Comment by dorr-fg** [comment]
This would be very helpful for me as well. For instance, for providing a "toolbar" for creating new entities in lookup fields that use this combo-box.

**Comment by plong0** [comment]
PR https://github.com/angular-ui/ui-select/pull/1323

Adds:
ui-select-header
ui-select-footer

**Comment by user378230** [comment]
Closing in favour of #1323 when it works.

**Pull request closed without merging**
