### PR TITLE
chore(refactor): split code into multiple files

### PR DESCRIPTION
**Pull request by dimirc**
I think it's time to split the code into different files to get more organized. Basically I split each main directive and service into different files and did a small change on the gulpfile to concat them when building.

I guess that this split might also help to avoid people pushing changes to /dist/select.js file and do the PR on the specific /src files

This is how it will look:
image

Later we should also reorganize the themes folders (check https://github.com/angular-ui/ui-select/issues/186)

Let me know your opinion

Related to: https://github.com/angular-ui/ui-select/issues/649

### CODE REVIEW

**Comment by dimirc** [comment]
@brianfeister @JeffGreat @starf @homerjam sorry to spam you, but as I see you active on this repo, can you give me your opinion on this PR? I know this will break most PRs that aren't merged but I think this will help to start organizing better all the project.

PD: This PR is failing because I merged https://github.com/angular-ui/ui-select/pull/651 (support for sort for multiselect) today and I should becase and create a new file uiSelectSortDirective.js

**Comment by dimirc** [comment]
I rebased this PR to last master, with a new file for sort directive:
image

**Comment by starf** [comment]
Don't count me as active, just a user trying to fix some of my issues while migrating from ui-select2. Looks to me to be much more manageable & readable like this.

**Comment by homerjam** [comment]
I guess I'm newly active! I think splitting up the files will certainly make things easier

**Comment by brianfeister** [comment]
This looks good to me @dimirc.  Would be a great time to think about how we generate distributions, whether the theme files can be broken out per the discussions in #175, #186, #529... obviously the scope of that is bigger, however.  My company just made the decision to move to Angular Material over Bootstrap, so it would be great to both include that as a new theme and also come up with a strategy for breaking out dependencies and having a way to reference different CSS and angular templates per theme #438

**Pull request merged**
