### PR TITLE
fix(uiSelectController): Select by click on non-multiple tagging

### LINKED ISSUE #1357: Can´t select elements with mouse click when using TAGGING
Hi,

I can not select any item of ui-select-choice list if I am using the tagging option.
Try out this example: https://github.com/angular-ui/ui-select/blob/master/examples/demo-tagging.html

Thanks.

### PR DESCRIPTION
**Pull request by soyuka**
When in tagging mode, not multiple (`taggingLabel === false`), selecting
an item by click was instead calling `taggingFunc()`. This fix checks
for this manual selection, whether `ctrl.search` is filled or not and
acts accordingly.

closes #1357

### CODE REVIEW

**Comment by soyuka** [comment]
Closes #1335 too

**Comment by soyuka** [comment]
Ping @aaronroberson would love to see this reviewed!

**Comment by aaronroberson** [comment]
I merged this in 4 hours ago and it will be included in the next release.

**Comment by rorlic** [comment]
In which release is this fix supposed to be included?

Looking at the [change set changes](https://github.com/angular-ui/ui-select/pull/1439/files), I do not see the changes in the latest release at this time: 0.18.1 (2016-07-10) nor any reference to this bug in the [change log](https://github.com/angular-ui/ui-select/blob/master/CHANGELOG.md).

**Comment by user378230** [comment]
@rorlic check the last referenced commit (3dfde71)

**Comment by rorlic** [comment]
OK, I see, the fix was "re-applied" after the last release.
So the real question is: when can we expect a new release? :-)

**Comment by aaronroberson** [comment]
@rorlic The updates have landed in v0.19.0

**Comment by rorlic** [comment]
Thanks! You guys rock.
Unfortunately, it is still not working correctly: when using tagging without label on a dropdown with 2 (or more) items (with or without an item being selected), if you select the second item by clicking it, the dropdown closes but the first one is selected. Selecting an item by using the keyboard works fine.

**Comment by aaronroberson** [comment]
@rorlic I pushed out v0.19.1 with the built files

**Comment by rorlic** [comment]
I have just verified it and it is working as expected. Thanks again.

**Pull request merged**
