### PR TITLE
fix(uiSelectCtrl) calculateContainerWidth use width of ui-select-container

### PR DESCRIPTION
**Pull request by bmsdave**
( not from body, if I set attribute `append-to-body=true`)

### CODE REVIEW

**Comment by bmsdave** [comment]
These four failing tests (which are not related to this PR) seem to happen on a fresh checkout from master now. Not sure why, but I think it's probably a dependency-version thing. I will be investigating further.

**Comment by pete-otaqui** [comment]
Related to #1872, suggest this PR should also account for actual padding of the field rather than a hard-coded 10px.

**Comment by pete-otaqui** [comment]
Also the failing tests are logged as #1877

**Comment by bmsdave** [comment]
@pete-otaqui, Hi.
I need some of the actions that have been adopted this PR?

**Comment by bmsdave** [comment]
@Jefiozie, @pete-otaqui, hi. This PR is actualy. Pls, tell me what I should do to the  issue #1874 was solved?

**Comment by Jefiozie** [comment]
I think you have added to much thing. Please clean up the select.js etc. Hope i can have a look later this week .

**Comment by bmsdave** [comment]
@JeffGreat, done.

**Comment by Jefiozie** [comment]
@bmsdave could you rebase this? Thanks

**Comment by bmsdave** [comment]
@Jefiozie, done.

**Comment by Jefiozie** [comment]
Could you also make a test around this? So that we now when behavior is changing? 

Thanks

**Comment by bmsdave** [comment]
Jefiozie, 
OK. I'll do everything on the weekend! =)

**Comment by Jefiozie** [comment]
Could you also have a look at: #1906 looks similar issue.

Thanks

**Comment by easyest** [comment]
This line is still not changed:
var inputWidth = containerWidth - input.offsetLeft - 10;

At least in bootstrap there is no need to subtract 10 px because input width should be the same as button width.

**Comment by bmsdave** [comment]
@Jefiozie, hi.
test and remove -10px is done.
plz, check it.

**Comment by Jefiozie** [comment]
Hi could you rebase this? After this I will merge the PR. Thanks

**Comment by bmsdave** [comment]
@Jefiozie, like that? i just resolve conflict.

**Pull request merged**
