### PR TITLE
Fix(resetSearchInput) change search box doesn't clear after selecting

### LINKED ISSUE #1484: Search box doesn't clear after selecting an option
In a tagging and multiple select input when you select an option the search input doesn't clear even when the reset-search-input is true.

The [documentation ](https://github.com/angular-ui/ui-select/wiki/ui-select) says: 
> reset-search-input : Clears the search box after selecting an option

More info here:
[Plunker](https://embed.plnkr.co/a8CLOUFTnPeYxBAF8JMB/)

### PR DESCRIPTION
**Pull request by Jefiozie**
This PR is instead of #1725.

Previously when the closeOnSelect was set to false the resetSearchInput was not executed after selecting a item even when resetSearchInput was set to true.

This fix will always execute the resetSearchInput when set to true even with the closeOnSelect set to false.

I believe this will fix #1484, #1083 , #1384, #777 and is making sure that #1015 is not needed.
@user378230 Did not test #1083 but as I believe will be fixed.

### CODE REVIEW

**Comment by user378230** [comment]
@Jefiozie I noticed that if you click an item it doesn't refocus the search area so you can't type in unless you manually click. 

Repro. Steps:
1. Type text (eg. "Y")
2. Click Yellow
3. Try typing... no work :disappointed: 

http://plnkr.co/edit/Cc9XuVRwWHWpVYpbIKCs?p=preview

*It works if you select with keyboard navigation though*

**Comment by Jefiozie** [comment]
Hi @user378230, I see it is not focusing the control . Should it always refocus on the control after selecting a option?  Or should this only be done if multiple is enabled?


p.s. the plunker you shared used v 0.13.1 btw

**Comment by user378230** [comment]
I didn't check single select use case actually but I think it should only refocus in multiple case. (I don't think people use `close-on-select=false` with single select mode anyway...)

And plunkr is against 0.19.4 I used can to update existing example from someone. 😛

**Comment by Jefiozie** [comment]
Okay I will fix it, when the `multiple `and` 'close-on-select=true'`  are used, the focus will be back at the control when the user has selected a item.

**Comment by user378230** [comment]
Thanks! If you could make plunkr with fixed version we can double check single select scenario too just to be sure 😃

**Comment by Jefiozie** [comment]
I think this will do? [Plunker focus](http://plnkr.co/edit/M3nm0irV5UmZwJyepHOk?p=preview)

**Pull request merged**
