### PR TITLE
Fix an error in multiple mode

### PR DESCRIPTION
**Pull request by MNBuyskih**
In multiple give an arror on startup, when there no selected items:
"TypeError: Cannot read property 'length' of undefined"

Sorry, my Sublime remove some trailing spaces. Actual changes on lines 58-60

### CODE REVIEW

**Comment by ckniffen** [comment]
+1

**Comment by nikolai-b** [comment]
`$select.selected` can be an empty array in which case it should also `return`.
I think #996 is a slightly better solution.

**Comment by cdjackson** [comment]
Probable duplicate of #956 and #996

**Comment by wesleycho** [comment]
Closing due to fix having already made it in `master`.

**Pull request closed without merging**
