### PR TITLE
fix(uiSelectMultipleDirective): add $isEmpty handler

### LINKED ISSUE #850: required tag
Is it possible to set a required tag for this control? I am not getting a prompt when the required tag is set and it is embedded in a form element. Thanks.

### PR DESCRIPTION
**Pull request by kmccullough**
Fixes #850

### CODE REVIEW

**Comment by aaronroberson** [comment]
@kmccullough Thanks, this will land in the next release!

**Comment by tmanoel** [comment]
Using single select and it's not working yet.. I'm Using version 0.19.0

**Comment by kmccullough** [comment]
@tmanoel I'm not sure what you are expecting. This fix is for ng-required not working on multiple selection. It should already work for single.

**Comment by tmanoel** [comment]
Thanks for the attention, kmccullough. But I'm using it into a directive. I've tried use required and ng-requeired, still not working for single select.

**Comment by tmanoel** [comment]
Take a look, it doesnt work on single neither multiple..
http://plnkr.co/edit/5Zt0OfEFh18tlcKP1Yen?p=preview

**Comment by kmccullough** [comment]
Can you give us a better idea of exactly what you are expecting in that plunkr @tmanoel ? It appears you are using version 0.11.2 of ui-select, which you have copied to an actual file included with the page, but it does not include my fix from this commit. Please try the latest version via CDN, update your sources with the latest, or apply my fix from *src/uiSelectMultipleDirective.js* to your own sources.

**Pull request merged**
