### PR TITLE
feat(ui-select-choices): expression based minimum-input-length

### PR DESCRIPTION
**Pull request by tystol**
Allows scope expressions to be used to calculate a minimum-input-length filter for the ui-select-choices directive.

Useful for showing all options when the option list is small, but applying a minimum when the list is large eg:

`minimum-input-length="people.length > 50 ? 3 : 0"`

### CODE REVIEW

**Comment by user378230** [comment]
Your indenting is slightly off. 

But I think maybe for consistency we follow the same pattern as the other observable attributes?..
```js
attrs.$observe('refreshDelay', function() {
  // $eval() is needed otherwise we get a string instead of a number
  var refreshDelay = scope.$eval(attrs.refreshDelay);
  $select.refreshDelay = refreshDelay !== undefined ? refreshDelay : uiSelectConfig.refreshDelay;
});
```

**Comment by tystol** [comment]
How's this?

**Comment by user378230** [comment]
That looks good now. 

Just to check, something like `minimum-input-length="{{people.length > 50 ? 3 : 0}}"` isn't supported already is it?

**Comment by tystol** [comment]
****facepalm****

I did try that first off directly within my app and it didn't work. Not sure what I did wrong, but it is working fine in this plunker:
http://plnkr.co/edit/K6EwjGZsetp4FsQEY9Hv?p=preview

So you can probably close this PR, unless there is any other reason to prefer the bracketless expressions?

**Comment by jamespsterling** [comment]
Still not working for me using the latest release, the $scope.$select.minimumInputLength variable is never updated after the initial assignment on load.

**Pull request closed without merging**
