### PR TITLE
feat(choices): use object as source iterating over its properties

### PR DESCRIPTION
**Pull request by dimirc**
We'll be able to use an object as the source for the choices (iterating over its properties)

Demo [plunker](http://plnkr.co/edit/9DsLidTZR7RJDEq6PW0H?p=preview])

Pending:
- [x] Need to add a watch to update choices when source object changes

### CODE REVIEW

**Comment by amcdnl** [comment]
Added docs here - https://github.com/angular-ui/ui-select/wiki/ui-select-choices

**Comment by amcdnl** [comment]
@dimirc It also does not work with 'nested' objects. The following setup:

		<ui-select ng-model="actionCtrl.model.action.delimeterType" style="width:100%">
			<ui-select-match>{{$select.selected}}</ui-select-match>
			<ui-select-choices repeat="type as (type, name) in actionCtrl.delimiterTypes | filter: $select.search">
			  <div ng-bind-html="name | highlight: $select.search"></div>
			</ui-select-choices>
		</ui-select>

tries to bind all the properties of `actionCtrl`. http://www.screencast.com/t/jMN4BZiI

**Comment by amcdnl** [comment]
@pdegenhardt @dimirc I have resolved the issues and release 0.13.2

**Comment by Avien** [comment]
Can you please check out issue #1255  I opened yesterday?
I have the exact same problem you described and upgraded to v0.13.2 but still not working
Thanks

**Comment by samuel-weber** [comment]
Hi amcdnl
Your Change #1208 broke the track by expression
Example: n in [42, 42, 43, 43] track by $index

https://github.com/angular-ui/ui-select/pull/1208

Greets Samuel

**Pull request merged**
