### PR TITLE
Update uiSelectController.js

### PR DESCRIPTION
**Pull request by chimmi**
Possible fix to #2054

### CODE REVIEW

**Comment by Jefiozie** [comment]
Can you build a test around it?

**Comment by chimmi** [comment]
Do you mean a test that proves that this fixes the issue?

**Comment by Jefiozie** [comment]
yes if you want 😄

**Comment by chimmi** [comment]
@Jefiozie Test should be as simple as this:
```
describe('Caret position', function () {
    it('should not change caret position in search field when selecting option with keyboard', function () {
      var el = createUiSelect(), searchField = $(el).find('.ui-select-search');
      openDropdown(el);
      setSearchText(el, 'ad');
      triggerKeydown(searchField, Key.Down);
      expect(searchField[0].selectionStart).toBe(2);
      searchField[0].setSelectionRange(0, 0);
      triggerKeydown(searchField, Key.Up);
      expect(searchField[0].selectionStart).toBe(0);
    });
  });
```
unfortunately `triggerKeydown(searchField, Key.Up);` does not seem to trigger carret move, so the test passes even without a fix.

**Pull request closed without merging**
