### PR TITLE
Prevent error when used with angular-animate <1.4 (Fixes #1415)

### LINKED ISSUE #1415: ui-select requires a newer version of angular than is listed in bower
the bower.json for ui-select lists:

`"dependencies": {
    "angular": ">=1.2.18"
  },`

but on line 355-356, it calls $animate.on which wasn't added till 1.4:

`if (ctrl.$animate && ctrl.$animate.enabled(container[0])) {
        ctrl.$animate.on('enter', container[0], function (elem, phase) {`

Adding "&& ctrl.$animate.on" would fix this, or obvious upping to angular 1.4

Also, noticed this issue too, not sure if it's related - #1306

### PR DESCRIPTION
**Pull request by jharting**
Fixes https://github.com/angular-ui/ui-select/issues/1415

### CODE REVIEW

**Comment by silentHoo** [comment]
Could anybody please merge this MR?

**Comment by halkeye** [comment]
Is there an earlier version that doesn't have this issue?

**Comment by jharting** [comment]
0.13.2 and before but these have other issues with ng-animate (see https://github.com/angular-ui/ui-select/commit/9db0a198ab3b3d1a66463f5bbd1f95ef5e0483aa)

**Comment by jharting** [comment]
Could anyone review and possibly merge this PR?

**Comment by silentHoo** [comment]
Hm, it's bad to know that this fix works but nobody wants to merge - that's not good :(

**Comment by aaronroberson** [comment]
@wesleycho Do you have permissions to publish updates to Bower? I only have permissions to publish changes to npm ATM.

**Comment by wesleycho** [comment]
Bower automatically publishes on new tag push.

I could potentially offer a bit of assistance in general - I merged this only because it looked correct, and I have prior experience with ngAnimate through my involvement in UI Bootstrap (and got bothered to merge it).

Project looks like it could use a lot of dev work though...but I guess this is a whole issue in itself.

**Comment by aaronroberson** [comment]
Yeah that is correct! @deeg has offered to help and the project would also benefit greatly from @user378230's direct help, as he's already proven to be a great help advising others on their PRs and replying to issues. I must not have access because I haven't been invited to the actual UI team organization yet (can you invite me)?

**Comment by wesleycho** [comment]
Done! Let me know if you didn't get the invite or if there's anything else I can do here.

**Comment by user378230** [comment]
I'd be happy to tidy up the issue log if given the relevant permissions :)

**Comment by aaronroberson** [comment]
@user378230 I've made you a contributor! Please keep in mind that we don't want to throw every perceivable feature and config option at the project and let it become something it was not intended to be. There are a ton of PRs, which if added, would add unwanted kludge and minutia to the project.

**Pull request merged**
