### PR TITLE
Stop propagation when pressing ENTER or ESC key from dropdown

### PR DESCRIPTION
**Pull request by loverajoel**
## What does this Pull Request Do?

Fix the event propagation when pressing enter or escape key from dropdown

## How should this be manually tested?

Run the tests and try the demos

## What are the relevant issues?

https://github.com/angular-ui/ui-select/issues/862

### CODE REVIEW

**Comment by dlsso** [comment]
+1

**Comment by Vitall** [comment]
+1

**Comment by t1mmen** [comment]
Thanks for this @loverajoel, looking forward to it being merged!

**Comment by just-boris** [comment]
+1
Once we make a component, we should take care about inner events and don't let them to affect other components

**Comment by just-boris** [comment]
there is one more relevant issue https://github.com/angular-ui/ui-select/issues/808

**Comment by reva2** [comment]
+1

**Comment by longzheng** [comment]
Thank you thank you thank you.

**Pull request merged**
