### PR TITLE
Change $select.clear() so it sets value to `null` instead of `undefined`

### PR DESCRIPTION
**Pull request by v-andrew**
Type: fix
Scope: uiSelectMatch

Fixes https://github.com/angular-ui/ui-select/issues/863

### CODE REVIEW

**Comment by v-andrew** [comment]
PR does not add more failing test.
Same tests are failing in the `master` branch.

**Comment by Jefiozie** [comment]
So i tested your adjustments and local i'm getting the same result. Can you double check at your end. 

Thanks.

**Comment by Jefiozie** [comment]
Hi @v-andrew  I think i have found the reason for the failing unit tests. Waiting for some comments why things have changed after this we can probably rebase your PR and the unit test problem will be resolved.

Thanks.

**Comment by v-andrew** [comment]
@Jefiozie Thanks
I can rebase it myself, just let me know, when CI issue solved

**Comment by Jefiozie** [comment]
HI @v-andrew , I have merged my PR could you rebase to the master?
Thanks.

**Comment by cloudrick** [comment]
Hi @v-andrew 

I have two problems:
1. If the repeat expression of ui-select-choices is like "<ui-select-choices repeat="o.name as o in XXX>",
the ngModel's value will still be undefined even if we set null to ctrl.
Maybe we need to modify ngModel.$parsers to skip handling for undefined and null
Ex:
```
// From view --> model
ngModel.$parsers.unshift(function (inputValue) {
  // Keep original value for undefined and null
  if (inputValue === undefined || inputValue === null) {
    return inputValue;
  }
  ......
});
```
2.  In ctrl.select(), does it need to handle null value as undefined value?
Ex:
```
  ctrl.select = function(item, skipFocusser, $event) {
    if (item === undefined || item === null || !_isItemDisabled(item)) {
    ......
```
Thanks

**Comment by v-andrew** [comment]
@Jefiozie sorry, for the delay, I'm quite busy.
Tests are passing now.

**Comment by v-andrew** [comment]
@cloudrick Let me look into it.

**Comment by Jefiozie** [comment]
Hi @v-andrew , any updates on this PR. Thanks.

**Comment by Jefiozie** [comment]
Any updates on this issue? 

Thanks

**Comment by jrbotros** [comment]
Happy to take this over if you're too busy, @v-andrew!

**Comment by Jefiozie** [comment]
@v-andrew can @jrbotros  have a look at this? based on your most recent updates you have not the time (at the moment) to finish this PR. Could @jrbotros  take over?


@jrbotros can you have a look it?

**Comment by Jefiozie** [comment]
@jrbotros Can you have a look at it?

**Comment by jrbotros** [comment]
@Jefiozie @v-andrew Happy to take this over, will look to get it finished in the next day or two!

**Comment by jrbotros** [comment]
@Jefiozie just submitted #1959, let me know what you think!
@v-andrew thanks for getting this started 😊

**Comment by Jefiozie** [comment]
Closing this down as we are continuing on #1959

**Pull request closed without merging**
