### PR TITLE
Add Allow-Clear support to Bootstrap Template

### PR DESCRIPTION
**Pull request by DanielClausen**
Bootstrap theme support for allow-clear attribute.

### CODE REVIEW

**Comment by howieweiner** [comment]
@bampakoa's suggestion works well, but in my case, it's not practical to add multiple methods to multiple controllers, so I wrote a child directive. Suits my purpose.

I'm wondering if this might not be a cleaner solution than attempting to rework the ui-select-match directive - considering the introduction of bootstrap columns caused so many issues?

Here's my directive: https://gist.github.com/howieweiner/f9db8d386a507defad2b

**Comment by abobwhite** [comment]
This works, but the styling is royally jacked up. See issues #578.

**Comment by dimirc** [comment]
Based on @bampakoa [comment](https://github.com/angular-ui/ui-select/pull/486#issuecomment-67307275) I pushed PR https://github.com/angular-ui/ui-select/pull/667

Demo [plunker](http://plnkr.co/edit/QGElZ3h8FV9g1Quf38pG?p=preview)

**Comment by howieweiner** [comment]
Unfortunately, this doesn't work in IE (10). The dropdown opens. I have the same issue with my directive mentioned above.. really can't work out how to prevent event propagation when the X is clicked

**Pull request merged**
