### PR TITLE
Limit the maximum number of selections allowed in multiple mode

### PR DESCRIPTION
**Pull request by cdjackson**
This adds a ```limit``` attribute to the directive to limit the number of selections allowed in multi select mode.

### CODE REVIEW

**Comment by dimirc** [comment]
Can you add a test?

**Comment by cdjackson** [comment]
Added a test to ensure that we limit selection to 2. We start with one selection, add another and check we have 2, then add another and check we still only have 2 selections.

**Comment by cambridgemike** [comment]
@dimirc Is this going out in the next maintenance release? If so, any ideas when that might be?

**Comment by mbajur** [comment]
@dimirc i've made a fork with build for that feature: https://github.com/mbajur/ui-select (release: `0.12.1-mb`)

**Comment by ganeshvelanki** [comment]
Is single select feature available ?

**Pull request merged**
