### PR TITLE
Add proper paste support

### PR DESCRIPTION
**Pull request by erikdubbelboer**
Add paste="expression" to allow custom paste handling.

Allow pasting in tagging mode when the tagging function is not defined.

In IE use window.clipboardData so jQuery is not required.

Fixes #910, #704, #789, #848, #429

### CODE REVIEW

**Comment by logannc** [comment]
Is there a reason that `ctrl.searchInput.value` is not used instead of the paste buffer? If not, you might miss things that are half-typed, half-pasted.

**Comment by ErikDubbelboer** [comment]
@logannc you are correct, I changed it so that the current input is prepended to the pasted data before parsing.

**Comment by danielgrippi** [comment]
bump. can we get this merged?

**Comment by aaronroberson** [comment]
Published in v0.14.7 if you would like to confirm.

**Comment by Hypercubed** [comment]
This is a useful feature and should be be documented.  I suggest the following added to the wiki:

| option | description | value | default |
|---|---|---|---|
| `paste` | Accepts a string which is a scope function. The function will be passed the new item as a string and should return an object which is the transformed value to be pushed to the items array. Returning false (or undefined) skips pushing to the items array.  | string ($scope function)| undefined |

**Comment by Hypercubed** [comment]
Actually, looking again it appears the return value is ignored..

**Comment by user378230** [comment]
@Hypercubed you should be able to update the wiki yourself, your contribution would be welcome! :smiley:

**Comment by Hypercubed** [comment]
Sure, was going to do that first... but wanted to make sure I understood the API.  My first assumtion was not correct.

**Pull request merged**
