### PR TITLE
solution for issue #1059 when searchEnabled is false.

### PR DESCRIPTION
**Pull request by cbryer**
when the search-enabled option on the ui-select directive is false the up, down and tab keys dont work.  this was because there was an ng-show="$select.searchEnabled" on the search input.  This change removes the ng-show and applies a css class to hide the search box using opacity and height styles.  Karma tests were updated and the following plunks demonstrate the changes.

previous:
http://plnkr.co/edit/zO8VFUUJTPnTRRh7u8kU?p=preview

with my changes:
http://plnkr.co/edit/3UpySUyaqi8fCbwB2OMi?p=preview

### CODE REVIEW

**Comment by dimirc** [comment]
Could you remove /dist files from this commit?
Also can you add changes from https://github.com/angular-ui/ui-select/pull/1109 to avoid bootstrap theme to look weird?

**Comment by cdjackson** [comment]
Just FYI, I've done a similar change in #1109 for the bootstrap theme. I used the 'offscreen' class to move  the search box off screen but still allow the focus to be set.

**Comment by cbryer** [comment]
I merged #1109 into this pull request.  I liked the idea of using offscreen class however selectize didnt render nicely and select2 theme needed the class applied to a containing div instead of the search input so i opted to keep the new css class and remove the code from the controller in #1109 that added the class directly to the input.

**Comment by cbryer** [comment]
is there anything else i should do for this pull request to get accepted?

**Pull request closed without merging**
