### PR TITLE
Fix Beforeunload issue on IE

### PR DESCRIPTION
**Pull request by elutz**
On IE, Beforeunload event is triggered when user picks an option from
the dropdown list, this can avoid by adding onclick="return false;" to
the link in the template of ui-select-choices list.

### CODE REVIEW

**Comment by elutz** [comment]
Related to issue #203

**Comment by dimirc** [comment]
Pls dont change/push any /dist file just files under /src

**Comment by elutz** [comment]
Sorry for that

**Comment by jguillen** [comment]
any chance this can be pull request can be merged in? Currently running into this issue on a project I am working on.

**Comment by clintam** [comment]
+1 for getting this merged. We are running into this issue on IE10 and I verified that this approach fixes it for us.

**Comment by clintam** [comment]
I think this could be abandoned. Issue appears fixed by https://github.com/angular-ui/ui-select/commit/fb88ec845355ad0c239a6bec3c284ad988d4af60

**Comment by wesleycho** [comment]
Closing as per @clintam's comment.

**Pull request closed without merging**
