### PR TITLE
feat(choices): allow user select group header

### PR DESCRIPTION
**Pull request by DarkIsDude**
User can now select header of group by option to select all item in this group

#1074 old pull request ref

### CODE REVIEW

**Comment by randdusing** [comment]
It would also be nice if the keyboard navigation supported this as well

**Comment by DarkIsDude** [comment]
Hi, we will use it in production. I must complete some task then I will changes this PR.

**Comment by DarkIsDude** [comment]
@Jefiozie thanks for your review. I just push a new commit to create a new directive (ui-select-header-group-selectable) that must be added on ui-select-choices directive with multiple and groups check.

It's my first PR, just say me if I must improve something.
You can find two comment
* Don't know why I must do this:
`var $select = select[0];`
* And if it's the good way to find the group:
`var group = $select.findGroupByName(element.text(), true);`

How can I create a plunker with my repo to show the result? How can I insert my select.js and select.css?

@randdusing I don't know where I can find the code that catch up keyboard event... Can you help me?

**Comment by randdusing** [comment]
I've heard this library is completely dead... so may not be worth investing time into a PR. I'm not exactly sure where the general keyboard handling is, but maybe try to find where DOWN is referenced.

**Comment by Jefiozie** [comment]
You can use the `examples plunkers` to fork the default ui-select example. Next copy your local build select.js etc in it and share the url.

The keyboard codes are in the `common.js`

**Comment by DarkIsDude** [comment]
@Jefiozie here the plunker: http://plnkr.co/edit/Ujr9amwp3hYMHwSgNdMT?p=preview to try it.
For the keyboard, it's a little bit more complicated. Maybe I will try it in an another PR.

Is it ok for you?

**Comment by Klinton90** [comment]
Just small request: can we make it optional? I.e. `scope: {isEnabled: "<uiSelectHeaderGroupSelectable"}`.

**Comment by DarkIsDude** [comment]
@Klinton90 the new plunker with your option: http://plnkr.co/edit/xtJ0SEGneWijtkc06hw5?p=preview.

**Comment by Klinton90** [comment]
Many thanks!

**Comment by kprabhuvel** [comment]
@DarkIsDude.. Even, I need this feature in my application. When do you think you can resolve and have a PR ready? Do you have a timeline when will it be ready? Please let me know.
-Prabhu

**Comment by Jefiozie** [comment]
@DarkIsDude Could you change something to test the build? Place the brackets on [line 3195](https://github.com/angular-ui/ui-select/pull/1998/commits/19a9b9a8595a3ed00467004581048ab9d9e5ce59#diff-26736c4d2d5d1e4c66b6e602618cb367R3195) and place it on [line 3203](https://github.com/angular-ui/ui-select/pull/1998/commits/19a9b9a8595a3ed00467004581048ab9d9e5ce59#diff-26736c4d2d5d1e4c66b6e602618cb367R3203)

I cannot reproduce it but it looks a bit off. (but maybe its just me 😄

**Comment by DarkIsDude** [comment]
@kprabhuvel, I work on it when I can, it's not a priority in our team...
I hope it will be ready soon but the build fail and I don't know why... @Jefiozie do you an idea?

**Comment by Jefiozie** [comment]
@DarkIsDude no I don't know why it does this. Merged other PR yesterday wasn't any problem there.  Looks like something is breaking for Firefox as it doesn't start.

**Comment by DarkIsDude** [comment]
So bad :( ... I just run `gulp test` on Firefox:
```browsers: ['Firefox'],```
on line 43 in karma.conf.js

And all pass... I don't know how can I fix it. Someone can help me?

**Comment by Jefiozie** [comment]
Hi @DarkIsDude could you merge the master in your branch and see if the issue is fixed?
Thanks

**Comment by DarkIsDude** [comment]
@Jefiozie yeah!!! It works. Well done. I'm waiting this PR is merged and after I will work on the keyboard navigation.

**Comment by Jefiozie** [comment]
Hi @DarkIsDude , 

Could you add a small part on the wiki that this is working from the upcoming version?
LGTM 👍

**Comment by DarkIsDude** [comment]
@Jefiozie did it ;).

**Comment by Klinton90** [comment]
Found couple related issues. PR is https://github.com/angular-ui/ui-select/pull/2069
It would be nice if @DarkIsDude  can review my changes in case I broke something.

**Pull request merged**
