### PR TITLE
select2 theme working well when the direction for the dropdown is set…

### LINKED ISSUE #1674: Select2 styles don't render dropdown is positioned 'up' and theme is globally set
### Select2 styles don't render dropdown is positioned 'up' and theme is globally set

[ Plunkr ](http://plnkr.co/edit/RgSNxa4bGTwdjABOoyDH?p=preview)

Click on the Always Up Select

### PR DESCRIPTION
**Pull request by hearsid**
Resolves #1674 , select2 theme working well when the direction for the dropdown is set to up, earlier it was working only when theme was set by the directive and not working for globally set theme

### CODE REVIEW

**Comment by user378230** [comment]
The definitions are the same as the ones already there for:
```
.ui-select-container[theme="select2"].direction-up ...
```
instead of duplicating the CSS can't you add another set of selectors for:
```
.ui-select-container.select2.direction-up ...
```
?

Also these changes should be made to `/src/common.css` not `/dist/select.css` please undo changes to `/dist` files and squash to single commit. 

Thanks

**Comment by hearsid** [comment]
Hello @user378230, 
1) Have added the css selectors to the existing CSS.
2) Have added the code to src/common.css
3) I also ran gulp build after making the change so that the changes get reflected in the dist folder files, please inform me if I have to undo that.

**Comment by user378230** [comment]
Please undo changes to all `/dist/` files

**Comment by user378230** [comment]
Can you format correctly? Standard practice is to place the new selector on a new line..

```css
.ui-select-container[theme="select2"].direction-up .ui-select-dropdown .select2-search,
.ui-select-container.select2.direction-up .ui-select-dropdown .select2-search {
```

**Comment by hearsid** [comment]
@user378230, thank you for the clear communication and quick reply, have made the change.

**Comment by user378230** [comment]
Thanks!

**Pull request merged**
