### PR TITLE
Added "limit-message" attribute. Displays a message instead of the selection list when multiple selection limit is reached.

### PR DESCRIPTION
**Pull request by DrCool**
I love the new "limit" feature which limits the number of items that can be selected on a multi-select.  But the user experience was a bit strange in that it didn't tell the user why they couldn't select any more items.  With this pull request, you can now specify a "limit-message" which tells the user why they can't choose any more items. If you leave it blank, it will use a simple default message.

The limit message will appear instead of the dropdown choice list. It can be easily styled using the new select2-selection-limit class.

See Plunker here: http://plnkr.co/edit/5YTzdYFsb7egwneuMl6P?p=preview

A unit test has been added and confirmed to work.

### CODE REVIEW

**Comment by DrCool** [comment]
I'm having trouble with the unit test.  It works fine on my computer but fails in the automated build when I push my changes to this commit.  I have no idea why.  Anyone have any thoughts?  I could really use someone's help.  I've tried to make this pull request as complete as possible so @dimirc is able to easily integrate the feature into the code.  Thanks everyone!

**Comment by wesleycho** [comment]
Can you try running the test locally with Firefox instead of Chrome? There may be something browser specific going on.

This needs squashing and rebasing as well.

**Comment by AshtonHylton-awin** [comment]
What happened with this?

**Comment by DrCool** [comment]
I'm getting back into this.  It's taking me some time to get karma up and running properly.  Once that's done, I need to rebase it and figure out why the test failed on Firefox but worked on Chrome.  Expect more news on this in the next week or so, depending on my time.  But it hasn't been abandoned.

**Comment by DrCool** [comment]
Re-submitted a new rebased version with a working unit test on pull request #1700

**Pull request closed without merging**
