### PR TITLE
Add option to allow duplicate items in multi-select

### PR DESCRIPTION
**Pull request by benri**
I added an option to allow selecting duplicate items for multi-select.

It's just an attribute on the ui-select level: 
```html
<ui-select multiple dupes="true/false" >...</ui-select>
```
and I copied the match-multiple templates with the only change that ng-repeat does `track by $index`

### CODE REVIEW

**Comment by JonesXavi** [comment]
@benri Thanks for your help. I had a similar issue now solved.

**Comment by LRPalacios** [comment]
is this done?

**Comment by chrisparton1991** [comment]
I requested this again in #1855 but it was rejected. I've implemented this feature in my local branch (see comment on that issue) and I'm using it successfully in a personal project.

Using npm, I'm specifying my dependency as `"ui-select": "chrisparton1991/ui-select#feat-duplicates-allowed"`. Feel free to use this in your own project, or vote for 1855 to be reopened if you think it'll be useful.

**Comment by Moshnogorskaya** [comment]
Thanks a lot! Your work helped me so much!

**Comment by mmoshnogorskaia** [comment]
> I requested this again in #1855 but it was rejected. I've implemented this feature in my local branch (see comment on that issue) and I'm using it successfully in a personal project.
> 
> Using npm, I'm specifying my dependency as `"ui-select": "chrisparton1991/ui-select#feat-duplicates-allowed"`. Feel free to use this in your own project, or vote for 1855 to be reopened if you think it'll be useful.

Thanks a lot! Your work helped me so much!

**Comment by chrisparton1991** [comment]
No problem @Moshnogorskaya, I'm glad it helped someone :)

If you're using my fork as an npm dependency like I did in my comment, you might want to consider making your own fork and applying the change there, just in case I ever delete my fork. I've rewritten my app with React, so I'm not using this code anymore.

**Comment by mmoshnogorskaia** [comment]
Thanks for a really quick answer and a good advice, Chris!
I will consider it:)

Have a great day!
Marina

ср, 7 нояб. 2018 г. в 15:09, Chris Parton <notifications@github.com>:

**Comment by mmoshnogorskaia** [comment]
Hello Chris!
Time passed and I forget to make a clone of your repository! Blame on me.
My project stopped building and the only hope that you may give your
repository somehow to clone.
I will greatly appreciate it!

Marina.

ср, 7 нояб. 2018 г. в 15:09, Chris Parton <notifications@github.com>:

**Comment by chrisparton1991** [comment]
Hi @Moshnogorskaya, I don't have a local copy of the repo sorry!

Can you take a look in your `node_modules` folder to see if you can find a copy of my `ui_select` in there? If so, could you zip it up and attach it here? We should be able to get you back up and running again.

Alternatively, my code from #1855 is still alive here: https://plnkr.co/edit/7KyteAUvcV8Yfw22CDo1?p=preview.

You could copy the `ui-select.js` file into your own project, remove my NPM dependency, and reference the file instead. This might be a simpler and better solution.

Let me know how you go!

**Comment by mmoshnogorskaia** [comment]
Thanks Chris!
I created my own repository from the data from  node modules and it works!
Have a good day!

чт, 11 июля 2019 г. в 2:07, Chris Parton <notifications@github.com>:

**Pull request closed without merging**
