### PR TITLE
refresh on active

### PR DESCRIPTION
**Pull request by abudel**
From #271, 
By setting to true the attribute "refresh-on-active" in the "ui-select-choiche", refresh method is called when the component is activated the first time.

### CODE REVIEW

**Comment by dimirc** [comment]
Can you add some tests?

**Comment by diogodomanski** [comment]
I've followed the instructions posted by abudel, but it didn't work.

**Comment by abudel** [comment]
Hi diogodomanski
you need to build the repository. Btw i made a <a href="http://plnkr.co/edit/2BvX52bOeqTy9SwJ06zx?p=preview">plunker</a> to see it in action.
Hope with this example you can figure it out.

**Comment by diogodomanski** [comment]
Thanks abudel. When will this feature be available in master branch?

**Comment by dimirc** [comment]
@abudel LGTM. As you might saw already, the source was split onto multiple files, can you rebase this PR so I can merge it? 

PD:Will be better if you just create a new branch from current master and apply all the changes, then just do a `git push origin --force` to overwrite the old commits

**Comment by abudel** [comment]
@dimirc thanks!  i updated the repo as you asked.

**Comment by Envek** [comment]
@abudel it's hard to test your changes as `dist/select.js` doesn't contain changes from `src/*.js` files (so it doesn't work), I had to patch `dist/select.js` manually in my app. After that everything worked :fireworks:! 
Please clean up your pull request: `dist/select.js` should contain only your changes and not 1000+ unrelated ones (it's not even possible to see diff on GitHub). Changes to `bower.json` and other files probably also shouldn't go into PR. You probably should do as @dimirc have said above (new branch, apply changes, forced push of new branch to this branch).

But thank you very much for your work! :+1: This PR will definitely fix my #619 issue after merging and publishing in bower.

**Comment by dimirc** [comment]
@abudel I still see changes to /dist files. Pls keep in mind that we should only change /src files. Also could you try to squash it all into one commit?

Let me know if you have any trouble on this changes.

**Comment by abudel** [comment]
@dimirc i don't get it. i tried to follow your instructions: <a href="https://github.com/abudel/ui-select/commit/33f4d9ff9b7c2bbd7abc1b0bb4dc7e8a877464fc" >33f4d9f</a>. Confused :confused:

**Comment by Envek** [comment]
@abudel In your fork's master branch (and it's specified as this PR branch) there is currently not only commit 33f4d9f but also another commits after it with various merges and so on. See your fork's [Network page](https://github.com/abudel/ui-select/network) for a visual representation.

If you do not need these extra commits in your fork's `master`, you can do the following:

    git checkout master             # Ensure we are on source branch
    git reset --hard 33f4d9f        # Cut it to this commit
    git push origin master --force  # Overwrite remote branch to be the same as local branch (to end with 33f4d9f)

After that contents of this PR will be updated. Please note that other commits from your master branch will disappear. If you do need these commits, please create a new branch from commit 33f4d9f and create a new PR from it (I see that there is a `refresh-on-active` branch).

This article from GitHub Help may help you: [Using pull requests](https://help.github.com/articles/using-pull-requests/)

**Comment by abudel** [comment]
@Envek thanks for your help. I followed your instructions.
@dimirc Now it should be ok.

**Comment by Envek** [comment]
@dimirc can you please take a look?
@abudel seems like it needs to be rebased.

**Comment by diogodomanski** [comment]
Can anyone fix these merge conflits and make this feature available in master branch? Thanks

**Comment by venkatesh13** [comment]
Really Usefull

**Comment by dmitry-dedukhin** [comment]
It's a must-have feature, could you please integrate it?

**Comment by banbanchs** [comment]
+1

**Comment by dmitry-dedukhin** [comment]
Hi.

Seems that this can be achieved by custom directive like the following:

```javascript
myModule.directive('uiSelectLazyLoad', function ($parse) {
    return {
        restrict: 'A',
        scope: true, // create new but not isolated scope
        compile: function (element, attrs) {
            var $choices = element.find('ui-select-choices'),
                refreshAttr = $choices.attr('refresh'),
                refreshFunc = null;

            if(!refreshAttr) {
                return;
            }

            refreshFunc = $parse(refreshAttr, /* interceptorFn */ null, /* expensiveChecks */ true);

            // replace all 'refresh' contents by own function
            $choices.attr('refresh', 'ptUiSelectLazyLoadHandler($event)');

            return function linkFn(scope, element, attrs) {
                var activated = false;

                element.one('click', function () {
                    activated = true;
                    scope.ptUiSelectLazyLoadHandler();
                });

                scope.ptUiSelectLazyLoadHandler = function ($event) {
                    if(!activated) {
                        return;
                    }
                    refreshFunc(scope);
                };
            };
        }
    };
});
```
The directive can be used like this:

```html
        <ui-select ng-model="dummy" ui-select-lazy-load>
            <ui-select-match>{{$select.selected.name}}</ui-select-match>
            <ui-select-choices
                    repeat="soft.id as soft in softs"
                    refresh="loadSoft($select.search)"
                    refresh-delay="200">
                <div ng-bind-html="soft.name | highlight: $select.search"></div>
            </ui-select-choices>
        </ui-select>
```
Function specified in "refresh" attribute on ```<ui-select-choices>``` will be called first time only after control "activation" i.e. after first click on ui-select.

**Comment by Gillardo** [comment]
+1, must have feature!

**Comment by nmeln** [comment]
+1

**Comment by Falldog** [comment]
+1

**Comment by maxzubr** [comment]
+1

**Comment by fabiopaiva** [comment]
+1

**Comment by ronaldotijucas** [comment]
+1

**Comment by krotkiewicz** [comment]
+1

**Comment by maiiku** [comment]
+1

**Comment by jefersondaniel** [comment]
+1

**Comment by shoutakenaka** [comment]
+1

**Comment by maxbundchen** [comment]
Will this feature be in the dist? It's a must-have!

**Comment by adrien-k** [comment]
+1

**Comment by dilerarc** [comment]
+1

**Comment by ftferes** [comment]
+1

**Comment by jeremypeters** [comment]
+1

**Comment by Gillardo** [comment]
when is this going to be pulled into master?

**Comment by PRISMAY** [comment]
+1

**Comment by oromand** [comment]
+1

**Comment by twizzzlers** [comment]
Why is this not pulled yet? Its an awesome feature... +1

**Comment by user378230** [comment]
@twizzzlers:

>This branch has conflicts that must be resolved

Note you could probably achieve this with custom directive such as:
```js
app.directive('refreshOnActivate', function() {
  return {
    require: 'uiSelect',
    link: function(scope, element, attrs, $select) {
      var _activate = $select.activate;     
      $select.activate = function (initSearchValue, avoidReset) {        
        _activate(initSearchValue, avoidReset);
        $select.refresh();
      }
    }
  };
});
```

**Comment by shyamal890** [comment]
Any update on this feature?

**Comment by user378230** [comment]
@shyamal890 My reply is literally just before yours! :sweat_smile:

**Comment by shyamal890** [comment]
@user378230 Thats right, but I was wondering when the solution would be added to master?

**Comment by user378230** [comment]
It can't be, as I said in my reply: **This branch has conflicts that must be resolved**

**Comment by kotmatpockuh** [comment]
+1

**Comment by fabiopaiva-praxis** [comment]
This works for me:

```js
app.directive('refreshOnActive', refreshOnActive);

function refreshOnActive() {
    return {
        restrict: 'A',
        link: refreshOnActiveLink,
        scope: {
            refreshOnActive: '=',
            refresh: '@'
        }
    }

    function refreshOnActiveLink(scope, element) {
        if (! scope.refreshOnActive === true) {
            return;
        }
        var storedFunction = scope.$parent.$select.refresh;
        scope.$parent.$select.refresh = function() {};

        var element = angular.element(element).closest('.ui-select-container');
        var fn = function() {
            scope.$parent.$select.refresh = function() {
                storedFunction(scope.refresh);
            };
            scope.$parent.$select.refresh.call();
            element.unbind('click', fn);
        };
        element.bind('click', fn);
    }
}
```

**Comment by Jefiozie** [comment]
As the PR #1845 is merged please verify if it fix your problem.

**Comment by Jefiozie** [comment]
Closing it down, if needed you can reopen it.
Thanks.

**Pull request closed without merging**
