### PR TITLE
Remove code that sizes search input to 10px

### PR DESCRIPTION
**Pull request by danieldaugherty**
This relates to issue [#1666](https://github.com/angular-ui/ui-select/issues/1666)

### CODE REVIEW

**Comment by voluntadpear** [comment]
this should be merged as soon as possible

**Comment by longzheng** [comment]
This has weird spacing changes

**Comment by danieldaugherty** [comment]
@longzheng my text editor is set to remove all trailing whitespace from files on save. I think it's weirder to have trailing whitespace in your files at all, but it's all the same when minified.

**Comment by aaronroberson** [comment]
@danieldaugherty Please remove code style and `dist` file changes. Also, I believe the 10px default is a hack to ensure that the the placeholder `hasLayout`.

Can you provide a plunkr so that this can be tested in multiple browsers to ensure that it doesn't cause a regression?

**Pull request closed without merging**
