### PR TITLE
Display loading text on refresh

### PR DESCRIPTION
**Pull request by kiddo13**
Loading text could be styled with css class .ui-select-refreshing.

### CODE REVIEW

**Comment by user378230** [comment]
Closing in favour of #1779 as it appears to be a better implementation/PR of similar functionality.

**Comment by gsaandy** [comment]
is it updated in the documentation?

**Comment by user378230** [comment]
@Jefiozie was there any updates to the wiki you need to make for #1779? Thanks :+1:

**Comment by Jefiozie** [comment]
@user378230   & @gsaandy Done 👍

**Comment by gsaandy** [comment]
looks like loading indication not working with multiple selection option.

**Comment by Jefiozie** [comment]
Can you share a plunjer with tour example?

**Pull request closed without merging**
