### PR TITLE
Display placeholder when searchEnable is set to false #241

### PR DESCRIPTION
**Pull request by hthabet**
fixes issue with displaying placeholder when searchEnable is set to false [#241]

### CODE REVIEW

**Comment by dtomaszewski** [comment]
+1

**Comment by evelez** [comment]
+1

**Comment by dimirc** [comment]
@dtomaszewski @evelez are can you setup a plunker to check this? what version of the lib are you using?

**Comment by hkorutla** [comment]
+1

**Comment by hkorutla** [comment]
I still have the same issue with "selectize" theme when search-enabled=false, placeholder is hiding. Any help would be appreciated.

**Pull request merged**
