### PR TITLE
Wrong input width calculated

### PR DESCRIPTION
**Pull request by easyest**
Search input width is currently calculated by subtracting 10 pixels from it's second parent width. But it should be the same, as the drop-down button width.

### CODE REVIEW

**Comment by Jefiozie** [comment]
Thanks for the PR, can you check why the tests are failing. 
Second please add a test  to test the behavior for now and in the future.

**Comment by Jefiozie** [comment]
HI @easyest , I have merged my PR could you rebase to the master?
Thanks.

**Comment by easyest** [comment]
I would be glad to do that, but I do not use git at all. This PR was done by a simple edit in the web form :)

**Comment by Jefiozie** [comment]
okay, i just saw that this is a duplicated issue. So closing it down as the other has a PR.

**Pull request closed without merging**
