### PR TITLE
Added ui-scroll

### PR DESCRIPTION
**Pull request by domakas**
* Added ui-scroll
* Added infinite scroller
* Added loader

### CODE REVIEW

**Comment by Mironor** [comment]
Looks like a fix for #221

**Comment by rahulmr999** [comment]
The ui-scroll is still not available right ? I don't see the changes in the latest build. Will this be fixed anytime soon ? I cannot migrate from ui-select2 because of this .:(

**Comment by PavelKonon** [comment]
+1

**Comment by scharfmedia** [comment]
+1, i  see this PR is a month old without feedback, any ETA for this?

**Comment by domakas** [comment]
I will try to add a example page for this when I have time, maybe it will be merged faster then.

**Comment by amcdnl** [comment]
Whats the premise behind adding ui-scroll vs just native?

**Comment by rahulmr999** [comment]
@domakas DId u get time to look into this ? I am not able to migrate because of this . Please .

**Comment by dimirc** [comment]
Is this adding a dependency to other library? we should avoid external dependency and maybe work on compatibility

**Comment by amcdnl** [comment]
I second that

**Comment by asm0dey** [comment]
If we should avoid dependency - maybe it's option to add this as separate bower module, that integrates with ui-scroll on one side and with ui-select on another?

**Comment by domakas** [comment]
Still haven't time to make the demo page, but I hope to make it soon.

Regarding dependencies, I implemented ui-scroll just because of #316 suggestion. Either way, it's optional, you don't have to add ui-scroll to your project if you are not using this scrolling feature.

**Comment by nlevari** [comment]
I wish I had a demo or a readme file instead of Digging the code for answers. Any ETA?

**Comment by amcdnl** [comment]
@domakas I see and totally see the value there....but I don't think thats the typical scenario and users of that would typically does a AJAX search instead.

@dimirc thoughts?

**Comment by rvoronyak** [comment]
Will this be merged into the master soon? ETA?

**Comment by jonathanchris** [comment]
@domakas Thanks for the work on this, but I need some assistance with an example or at least just how this would look to get it working. Specifically with the infinite attribute, I can't seem to put anything in there  that works. So far i've pulled down your branch, built it, and put it in my source. Then tried to add it to an existing working ui-select example but i'm not getting any results.

**Comment by PowerKiKi** [comment]
@scharfmedia, @nlevari, @rvoronyak without any tests nor documentation, the chances to get it merged seem pretty slim

**Comment by hummorsa** [comment]
Hi, is his going to be included in the ui-select at all ? or is something was cancelled ?

**Comment by amcdnl** [comment]
@hummorsa No, I do not believe so.  It doesn't fit in with the vision of ui-select.  I'd advise @domakas to make a public repo that includes this and I'll cite it in the docs.

**Comment by mlibanori** [comment]
how use ui-select + ui-scroll ?? is there some example ??

**Comment by filipe3oliveira** [comment]
@domakas how can we use this?

**Comment by domakas** [comment]
Sorry for delayed response for all of you. After some time working with this, it's still buggy and probably shouldn't be used yet. This requires big time effort to make it work properly, which I don't have at the moment. I will try to dig down a demo page, so someone maybe could continue working on this.

Sorry for all the fuss.

**Pull request closed without merging**
